/**
 * agents/visual-feature-validator.ts
 *
 * Character Ontology Layer Separation: Visual / Psychological / Narrative
 *
 * RULE: Only visually observable features may enter image generation.
 * Personality, psychology, morality, and story traits are STRICTLY FORBIDDEN.
 *
 * TRUE  = can be observed by a camera, drawn by an artist, generated by an image model
 * FALSE = abstract trait, personality label, moral judgment, internal state
 */

const NON_VISUAL_PATTERNS = [
  // Personality traits (性格/人格)
  /重情义|重感情|有情有义|义气|仗义|忠诚|忠心|忠厚|老实|正直|正义|正派/i,
  /善良|善解人意|体贴|温柔|温和|和蔼|和善|亲切|随和|开朗|乐观|积极|上进/i,
  /敏感|细腻|细心|细致|谨慎|小心|稳重|沉稳|冷静|镇定|从容/i,
  /内向|外向|活泼|好动|安静|文静|羞涩|害羞|腼腆|坦率|直率|直爽/i,
  /固执|倔强|执拗|顽固|任性|急躁|暴躁|冲动|鲁莽|冒失|轻率/i,
  /坚强|坚韧|顽强|勇敢|果断|独立|自信|自强|自律/i,
  /聪明|智慧|机灵|机智|灵活|敏锐|精明|能干|有才华|有天赋/i,
  /浪漫|幽默|风趣|诙谐|洒脱|豪爽|大方|慷慨|节俭|朴素/i,
  /有责任感|有担当|负责任|可靠|可信|值得信赖|靠谱|踏实/i,
  /有魅力|有气质|有风度|优雅|高贵|端庄|儒雅|斯文/i,
  /自私|自利|小气|吝啬|贪婪|虚伪|狡猾|阴险|狠毒|残忍|冷酷|无情|冷漠|冷淡/i,
  /心机|城府|深算|算计|阴谋|诡计|奸诈|狡诈/i,

  // Moral/ethical traits (品德)
  /高尚|崇高|伟大|无私|奉献|大度|宽容|忍让|谦让|谦虚|谦卑|卑劣|卑鄙/i,
  /正直|诚实|诚信|真诚|真挚|恳切|敦厚|淳朴|憨厚/i,

  // Psychological states (心理状态)
  /焦虑|抑郁|压抑|苦闷|烦恼|忧愁|忧伤|悲伤|悲痛|哀伤/i,
  /孤独|寂寞|落寞|失落|沮丧|绝望|无助|迷茫|困惑|矛盾|纠结/i,
  /紧张|恐慌|恐惧|害怕|担心|不安|烦躁|厌倦|疲惫|疲倦/i,
  /渴望|期待|向往|憧憬|幻想|梦想|希望|绝望/i,
  /满足|幸福|快乐|高兴|愉悦|欢喜|欣喜|得意|骄傲|自豪/i,

  // Emotional patterns (情绪模式)
  /情绪化|情感丰富|多愁善感|易怒|暴躁|易冲动|易焦虑/i,
  /内心|心底|心中|心里|心灵|灵魂|精神|思想|思维|念头|想法|观念/i,

  // Motivation/values (动机/价值观)
  /有理想|有抱负|有追求|有目标|有信仰|有信念|有原则|有底线|有立场/i,
  /上进心|事业心|责任心|荣誉感|使命感|正义感|道德感/i,

  // Abstract identity labels (抽象身份标签)
  /学霸|学渣|宅男|宅女|文艺青年|愤青|屌丝|白富美|高富帅/i,
]

const VISUAL_KEYWORDS = [
  // Physical features that CAN be observed
  '高', '矮', '胖', '瘦', '壮', '健', '魁梧', '娇小', '苗条', '丰满',
  '长', '短', '卷', '直', '黑', '白', '黄', '棕', '金', '红', '蓝', '紫', '灰',
  '戴', '穿', '披', '系', '绑', '扎', '梳',
  '眼', '眉', '鼻', '嘴', '唇', '耳', '脸', '额', '颊', '腮', '下颌',
  '皱纹', '疤痕', '痣', '斑', '痘', '胡须', '胡子',
  '眼镜', '项链', '耳环', '戒指', '手表', '手链', '手镯', '脚链',
  '衣', '服', '衫', '裤', '裙', '帽', '鞋', '袜', '带', '扣',
  '色', '肤', '肌', '骨', '肩', '背', '胸', '腰', '腹', '臀', '腿', '手', '脚',
]

export function isVisualFeature(value: string): boolean {
  // Short values (<3 chars) are not meaningful visual descriptions
  if (!value || value.length < 2) return false

  // Check against non-visual patterns
  for (const pattern of NON_VISUAL_PATTERNS) {
    if (pattern.test(value)) return false
  }

  // Must contain at least one visual keyword or describe observable traits
  const hasVisualKeyword = VISUAL_KEYWORDS.some(kw => value.includes(kw))
  if (hasVisualKeyword) return true

  // If no visual keyword, check description structure:
  // It should describe something observable (length, color, shape, material)
  const observablePatterns = /[长短高矮胖瘦粗细深浅]|[颜色色调]|穿[着戴]|有[一双张个]|[,，、\s]/

  // Allow longer descriptions that include concrete details
  if (value.length > 8 && observablePatterns.test(value)) return true

  // Pure abstract traits fail
  return false
}

export function validateVisualFeatures(features: { type: string; value: string }[]): { type: string; value: string }[] {
  return features.filter(f => {
    if (f.type === 'expression' || f.type === 'personality' || f.type === 'trait') {
      return isVisualFeature(f.value)
    }
    return true // non-expression types are already visual
  })
}

export function validatePromptInput(character: any): { valid: boolean; rejected: string[] } {
  const rejected: string[] = []
  if (character.personality) {
    for (const trait of character.personality) {
      if (!isVisualFeature(trait)) {
        rejected.push(trait)
      }
    }
  }
  return { valid: rejected.length === 0, rejected }
}
