/**
 * SOUL.md Generator Service — ER-04-TASK-02
 * AI Employee Persona Template Engine
 *
 * 职责: 根据 Employee Profile 自动生成 Hermes SOUL.md
 * 架构: 模板填充 + 权限映射 (只读，不修改 Runtime)
 *
 * 数据来源:
 *   EnterpriseAgentProfile → 身份/角色/能力/权限
 *   HermesProfileBinding → 绑定信息
 */
import { prisma } from '../../utils/index.js'

// ─── Types ───────────────────────────────────────────────

export interface SoulTemplate {
  identity: string
  mission: string
  responsibilities: string[]
  capabilities: string[]
  boundaries: string[]
  executionRules: string[]
  raw: string
}

// ─── Service ─────────────────────────────────────────────

export class SoulGeneratorService {

  /**
   * 根据 Employee Profile 生成 SOUL.md
   */
  async generateSoul(organizationId: string, agentId?: string): Promise<SoulTemplate> {
    // 1. 获取 Employee Profile
    const agent = agentId
      ? await prisma.enterpriseAgentProfile.findFirst({
          where: { id: agentId, organizationId },
        })
      : await prisma.enterpriseAgentProfile.findFirst({
          where: { organizationId, isDefault: true },
        })

    if (!agent) {
      throw new Error('AGENT_NOT_FOUND')
    }

    // 2. 获取组织信息
    const org = await prisma.organization.findUnique({
      where: { id: organizationId },
    })

    // 3. 解析能力/权限
    const capabilities = this.parseJSON<string[]>(agent.capabilities, [])
    const permissions = this.parseJSON<string[]>(agent.permissions, [])
    const tools = this.parseJSON<string[]>(agent.tools, [])

    // 4. 生成各段落
    const identity = this.generateIdentity(agent, org?.name || 'Unknown')
    const mission = this.generateMission(agent)
    const responsibilities = this.generateResponsibilities(agent, capabilities)
    const caps = this.generateCapabilities(capabilities, tools)
    const boundaries = this.generateBoundaries(organizationId, permissions)
    const executionRules = this.generateExecutionRules(permissions)

    // 5. 组装完整 SOUL.md
    const raw = [
      `# ${agent.name} — ${this.translateRole(agent.role)}`,
      '',
      '## Identity',
      `- Role: ${this.translateRole(agent.role)}`,
      `- Organization: ${org?.name || organizationId}`,
      `- Agent ID: ${agent.id}`,
      '',
      '## Mission',
      agent.goal || '执行企业分配的任务',
      '',
      '## Responsibilities',
      ...responsibilities.map((r) => `- ${r}`),
      '',
      '## Capabilities',
      ...caps.map((c) => `- ${c}`),
      '',
      '## Boundaries',
      ...boundaries.map((b) => `- ${b}`),
      '',
      '## Execution Rules',
      ...executionRules.map((r) => `- ${r}`),
      '',
      '## Persona',
      `- Personality: ${this.derivePersonality(agent.agentType)}`,
      `- Communication Style: 专业、简洁、数据驱动`,
      `- Language: 中文为主`,
      '',
      '---',
      `*Generated by KunLunJing OS at ${new Date().toISOString()}*`,
    ].join('\n')

    return {
      identity,
      mission,
      responsibilities,
      capabilities: caps,
      boundaries,
      executionRules,
      raw,
    }
  }

  /**
   * 根据 agentType 生成 SOUL.md
   */
  async generateSoulByType(organizationId: string, agentType: string): Promise<SoulTemplate> {
    const agent = await prisma.enterpriseAgentProfile.findFirst({
      where: { organizationId, agentType },
    })
    if (!agent) {
      throw new Error('AGENT_TYPE_NOT_FOUND')
    }
    return this.generateSoul(organizationId, agent.id)
  }

  // ─── Private: Section Generators ───────────────────────

  private generateIdentity(agent: any, orgName: string): string {
    return `${agent.name} — ${this.translateRole(agent.role)} @ ${orgName}`
  }

  private generateMission(agent: any): string {
    return agent.goal || `执行 ${this.translateRole(agent.role)} 相关任务`
  }

  private generateResponsibilities(agent: any, capabilities: string[]): string[] {
    const base: string[] = []

    // 从 capabilities 映射职责
    const capMap: Record<string, string> = {
      '销售分析': '分析销售数据，发现增长机会',
      '客户预测': '预测客户行为，识别高价值客户',
      '自动报价': '根据客户需求自动生成报价方案',
      'CRM管理': '维护客户关系管理系统',
      '内容创作': '创作营销内容和推广文案',
      '数据分析': '执行数据分析和洞察挖掘',
      '市场研究': '研究市场趋势和竞争格局',
      '客户运营': '执行客户触达和互动活动',
    }

    for (const cap of capabilities) {
      base.push(capMap[cap] || `执行 ${cap} 相关任务`)
    }

    if (base.length === 0) {
      base.push('执行企业分配的任务')
    }

    return base
  }

  private generateCapabilities(capabilities: string[], tools: string[]): string[] {
    const caps: string[] = []

    for (const cap of capabilities) {
      caps.push(cap)
    }

    for (const tool of tools) {
      // 将工具名称映射为能力描述
      const toolDesc = this.translateTool(tool)
      if (!caps.includes(toolDesc)) {
        caps.push(toolDesc)
      }
    }

    return caps
  }

  private generateBoundaries(organizationId: string, permissions: string[]): string[] {
    const boundaries: string[] = []

    // 组织隔离
    boundaries.push(`Organization: ${organizationId} only`)
    boundaries.push('No cross-tenant data access')
    boundaries.push('No cross-organization memory sharing')

    // 权限边界
    if (!permissions.includes('data_export')) {
      boundaries.push('No unauthorized data export')
    }
    if (!permissions.includes('admin')) {
      boundaries.push('No administrative actions')
      boundaries.push('No system configuration changes')
    }

    // 通用边界
    boundaries.push('Require approval for destructive actions')
    boundaries.push('Log all operations to audit trail')
    boundaries.push('Respect tool permission matrix')

    return boundaries
  }

  private generateExecutionRules(_permissions: string[]): string[] {
    return [
      'Verify organization context before any action',
      'Require CEO approval for data deletion',
      'Rate limit: max 100 API calls per hour',
      'Escalate failures after 3 retries',
      'Maintain audit trail for all operations',
      'Report outcome to KunLunJing after completion',
    ]
  }

  // ─── Private: Translations ─────────────────────────────

  private translateRole(role: string): string {
    const map: Record<string, string> = {
      growth_director: '增长总监',
      market_analyst: '市场分析师',
      content_manager: '内容增长专员',
      customer_ops: '客户运营专员',
      sales_assistant: '销售参谋专员',
      sales: '销售 AI',
      marketing: '营销 AI',
      support: '客服 AI',
      analyst: '分析 AI',
      content: '内容 AI',
      customer_success: '客户成功 AI',
    }
    return map[role] || role
  }

  private translateTool(tool: string): string {
    const map: Record<string, string> = {
      'CRM读写': 'CRM 数据读写',
      '客户分析': '客户行为分析',
      '方案生成': '解决方案生成',
      '数据导出': '数据导出操作',
      '客户触达': '客户沟通触达',
      '报告生成': '业务报告生成',
      '财务分析': '财务数据分析',
    }
    return map[tool] || tool
  }

  private derivePersonality(agentType: string): string {
    const map: Record<string, string> = {
      growth_director: '战略思维、结果导向',
      market_analyst: '数据驱动、严谨分析',
      content_manager: '创意丰富、表达清晰',
      customer_ops: '耐心细致、服务导向',
      sales_assistant: '积极主动、说服力强',
    }
    return map[agentType] || '专业、高效、可靠'
  }

  private parseJSON<T>(val: string | null | undefined, fallback: T): T {
    if (!val) return fallback
    if (typeof val === 'object') return val as T
    try { return JSON.parse(val) } catch { return fallback }
  }
}

export const soulGeneratorService = new SoulGeneratorService()
