const tsx = '/root/.npm/_npx/fd45a72a545557e9/node_modules/.bin/tsx'

module.exports = {
  apps: [
    { name: 'api-server-0', script: '/root/shipin-cinematic-studio/backend/src/index.ts',
      cwd: '/root/shipin-cinematic-studio/backend',
      interpreter: tsx, interpreter_args: '--experimental-default-type=commonjs',
      env: { PORT: 4002 },
      max_memory_restart: '2G',
      max_restarts: 8,
      restart_delay: 3000,
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      error_file: '/root/.pm2/logs/api-server-error.log',
      out_file: '/root/.pm2/logs/api-server-out.log',
      merge_logs: true,
      max_size: '50M',
      retain: 5,
    },
    { name: 'api-server-1', script: '/root/shipin-cinematic-studio/backend/src/index.ts',
      cwd: '/root/shipin-cinematic-studio/backend',
      interpreter: tsx, interpreter_args: '--experimental-default-type=commonjs',
      env: { PORT: 4003 },
      max_memory_restart: '2G', max_restarts: 8, restart_delay: 3000,
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      error_file: '/root/.pm2/logs/api-server-error.log',
      out_file: '/root/.pm2/logs/api-server-out.log',
      merge_logs: true, max_size: '50M', retain: 5,
    },
    { name: 'api-server-2', script: '/root/shipin-cinematic-studio/backend/src/index.ts',
      cwd: '/root/shipin-cinematic-studio/backend',
      interpreter: tsx, interpreter_args: '--experimental-default-type=commonjs',
      env: { PORT: 4004 },
      max_memory_restart: '2G', max_restarts: 8, restart_delay: 3000,
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      error_file: '/root/.pm2/logs/api-server-error.log',
      out_file: '/root/.pm2/logs/api-server-out.log',
      merge_logs: true, max_size: '50M', retain: 5,
    },
    { name: 'api-server-3', script: '/root/shipin-cinematic-studio/backend/src/index.ts',
      cwd: '/root/shipin-cinematic-studio/backend',
      interpreter: tsx, interpreter_args: '--experimental-default-type=commonjs',
      env: { PORT: 4005 },
      max_memory_restart: '2G', max_restarts: 8, restart_delay: 3000,
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      error_file: '/root/.pm2/logs/api-server-error.log',
      out_file: '/root/.pm2/logs/api-server-out.log',
      merge_logs: true, max_size: '50M', retain: 5,
    },
    { name: 'api-server-4', script: '/root/shipin-cinematic-studio/backend/src/index.ts',
      cwd: '/root/shipin-cinematic-studio/backend',
      interpreter: tsx, interpreter_args: '--experimental-default-type=commonjs',
      env: { PORT: 4006 },
      max_memory_restart: '2G', max_restarts: 8, restart_delay: 3000,
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      error_file: '/root/.pm2/logs/api-server-error.log',
      out_file: '/root/.pm2/logs/api-server-out.log',
      merge_logs: true, max_size: '50M', retain: 5,
    },
    { name: 'api-server-5', script: '/root/shipin-cinematic-studio/backend/src/index.ts',
      cwd: '/root/shipin-cinematic-studio/backend',
      interpreter: tsx, interpreter_args: '--experimental-default-type=commonjs',
      env: { PORT: 4007 },
      max_memory_restart: '2G', max_restarts: 8, restart_delay: 3000,
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      error_file: '/root/.pm2/logs/api-server-error.log',
      out_file: '/root/.pm2/logs/api-server-out.log',
      merge_logs: true, max_size: '50M', retain: 5,
    },
  ],
}
