// ============================================================
// Identity Bootstrap Service v2.0
// Enterprise OS Identity Recovery — P0-3-05 Phase A
// ============================================================
// 决策变更记录（SPRINT-IDENTITY-REALITY-01, 2026-08-01 掌柜指令）:
// 旧决策(Phase 3.2 CTO): governance_organization 为唯一 Source of Truth
// 新决策(掌柜): Organization 表 = 唯一企业身份 SSOT（商业主体：订阅/权益/员工/实例/任务）
//   governance_organization/tenant/user = 组织架构辅助体系（部门树+成员），不产生企业身份业务
// 冻结: EnterpriseMember / EnterpriseTenant / CustomerOrg 不产生新业务逻辑
// 禁止写入 Organization / OrgMember 表 的旧决策已解除（OrgMember = OrganizationMember，正常使用）
// ============================================================

import { prisma } from '../../../utils/index.js'

export interface IdentityBootstrapResult {
  userId: string
  organizationId: string
  organizationName: string
  role: string
  isNewOrganization: boolean
  isNewMembership: boolean
}

/**
 * 确保用户拥有 governance_organization 关联
 * P0-3-05 Phase A: 不再写入 Organization/OrgMember 已冻结表
 * 
 * 链路: User(email) → governance_user → governance_tenant → governance_organization
 * 
 * BETA-06.1.3: 不再自动创建企业（禁止 User.username → Organization.name）
 * 如果用户没有 Organization，返回 hasOrganization: false，由前端引导初始化
 */
export async function ensureOrganizationForUser(userId: string, userName?: string): Promise<IdentityBootstrapResult> {
  // 1. 获取当前用户
  const user = await prisma.user.findUnique({ where: { id: userId } })
  if (!user) {
    throw new Error('User not found')
  }

  // 2. 通过 email 找到 governance_user
  const govUser = await prisma.govUser.findFirst({
    where: { email: user.email },
  })

  // 3. 获取用户组织的 governance_organization
  if (govUser?.tenantId) {
    const existingOrg = await prisma.govOrganization.findFirst({
      where: { tenantId: govUser.tenantId },
    })

    if (existingOrg) {
      // BETA-06.1.3: 检测是否为"未初始化"状态（自动生成的 username + ' 的企业'）
      const isUninitialized = isAutoGeneratedName(existingOrg.name, user)
      
      return {
        userId,
        organizationId: existingOrg.id,
        organizationName: isUninitialized ? '' : existingOrg.name,
        role: 'OWNER',
        isNewOrganization: false,
        isNewMembership: false,
      }
    }
  }

  // BETA-06.1.3: 不再自动创建企业
  // 返回 null organizationId，前端将展示"创建企业"引导
  return {
    userId,
    organizationId: '',
    organizationName: '',
    role: 'OWNER',
    isNewOrganization: false,
    isNewMembership: false,
  }
}

/**
 * BETA-06.1.3: 检测企业名称是否为自动生成的（username + ' 的企业'）
 * 如果是，说明用户尚未真正创建企业信息
 */
function isAutoGeneratedName(orgName: string, user: { username: string | null; email: string | null }): boolean {
  if (!orgName) return true
  const patterns = [
    user.username ? `${user.username} 的企业` : '',
    user.email ? `${user.email} 的企业` : '',
    user.email ? `${user.email.split('@')[0]} 的企业` : '',
    '我的企业',
  ]
  return patterns.some(p => p && orgName === p)
}

/**
 * BETA-06.1.3: 创建真正的企业信息
 * 由前端"创建企业"引导流程调用
 */
export async function createOrganization(input: {
  userId: string
  name: string
  industry?: string
  description?: string
  logo?: string
  size?: string
}): Promise<IdentityBootstrapResult> {
  const user = await prisma.user.findUnique({ where: { id: input.userId } })
  if (!user) throw new Error('User not found')

  // 检查是否已有组织（避免重复创建）
  const govUser = await prisma.govUser.findFirst({ where: { email: user.email } })
  
  if (govUser?.tenantId) {
    const existingOrg = await prisma.govOrganization.findFirst({ where: { tenantId: govUser.tenantId } })
    if (existingOrg) {
      // 更新已有组织
      const updated = await prisma.govOrganization.update({
        where: { id: existingOrg.id },
        data: {
          name: input.name,
          metadata: JSON.stringify({
            industry: input.industry || '',
            description: input.description || '',
            logo: input.logo || '',
            size: input.size || '',
            initialized: true,
            initializedAt: new Date().toISOString(),
          }),
        },
      })
      return {
        userId: input.userId,
        organizationId: updated.id,
        organizationName: updated.name,
        role: 'OWNER',
        isNewOrganization: false,
        isNewMembership: false,
      }
    }
  }

  // 创建新组织
  let tenantId = govUser?.tenantId
  if (!tenantId) {
    const newTenant = await prisma.tenant.create({
      data: { name: input.name, type: 'enterprise' },
    })
    tenantId = newTenant.id
  }

  const newOrg = await prisma.govOrganization.create({
    data: {
      name: input.name,
      tenantId,
      type: 'enterprise',
      departmentRole: 'ai_department',
      status: 'active',
      metadata: JSON.stringify({
        industry: input.industry || '',
        description: input.description || '',
        logo: input.logo || '',
        size: input.size || '',
        initialized: true,
        initializedAt: new Date().toISOString(),
      }),
    },
  })

  return {
    userId: input.userId,
    organizationId: newOrg.id,
    organizationName: newOrg.name,
    role: 'OWNER',
    isNewOrganization: true,
    isNewMembership: true,
  }
}

/**
 * 获取用户的 governance_organization ID
 * P0-3-05 Phase A: User → email → govUser → tenant → org
 */
export async function getOrganizationIdForUser(userId: string): Promise<string | null> {
  // 1. 通过 User ID 获取用户邮箱
  const user = await prisma.user.findUnique({
    where: { id: userId },
    select: { email: true },
  })
  
  if (!user?.email) return null

  // 2. 通过 email 找到 governance_user
  const govUser = await prisma.govUser.findFirst({
    where: { email: user.email },
    select: { tenantId: true },
  })

  if (!govUser?.tenantId) return null

  // 3. 通过 tenantId 找到 governance_organization
  const org = await prisma.govOrganization.findFirst({
    where: { tenantId: govUser.tenantId },
    select: { id: true },
  })

  return org?.id || null
}

/**
 * 解析用户身份链：User → email → govUser → tenantId
 * C1: Security Boundary 专用，无 user.id fallback
 */
export async function resolveTenantIdForUser(userId: string | undefined): Promise<string | null> {
  if (!userId) return null

  const user = await prisma.user.findUnique({
    where: { id: userId },
    select: { email: true },
  })

  if (!user?.email) return null

  const govUser = await prisma.govUser.findFirst({
    where: { email: user.email },
    select: { tenantId: true },
  })

  return govUser?.tenantId || null
}

/**
 * 获取用户的 governance_organization 信息
 */
export async function getOrganizationForUser(userId: string) {
  const user = await prisma.user.findUnique({
    where: { id: userId },
    select: { email: true },
  })
  
  if (!user?.email) return null

  const govUser = await prisma.govUser.findFirst({
    where: { email: user.email },
    select: { tenantId: true },
  })

  if (!govUser?.tenantId) return null

  const org = await prisma.govOrganization.findFirst({
    where: { tenantId: govUser.tenantId },
  })

  return org ? { id: org.id, name: org.name, role: 'OWNER' } : null
}
