export { DiscoveryService, discoveryService } from './discovery.service.js'
export type { DiscoveryProvider } from './discovery-provider.js'
export { LegacyMockProvider } from './legacy-mock-provider.js'
export { Engine2Provider } from './engine2-provider.js'
export { getDiscoveryProvider, refreshDiscoveryProvider, getDiscoveryVersion } from './provider-factory.js'
export { DiscoveryValidator, discoveryValidator } from './discovery-validator.js'
export type { ValidationReport, ValidationError } from './discovery-validator.js'
export { DiscoveryMetricsCollector, discoveryMetrics } from './discovery-metrics.js'
export type { DiscoveryMetricsRecord, StageMetrics, ProviderMetrics } from './discovery-metrics.js'
