// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 8/3/2026, 2:17:31 AM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/root/shipin-cinematic-studio/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/root/shipin-cinematic-studio/frontend/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/root/shipin-cinematic-studio/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/root/shipin-cinematic-studio/frontend/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/root/shipin-cinematic-studio/frontend/plugins/**/*.{js,ts,mjs}","/root/shipin-cinematic-studio/frontend/composables/**/*.{js,ts,mjs}","/root/shipin-cinematic-studio/frontend/utils/**/*.{js,ts,mjs}","/root/shipin-cinematic-studio/frontend/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/root/shipin-cinematic-studio/frontend/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/root/shipin-cinematic-studio/frontend/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/root/shipin-cinematic-studio/frontend/app.config.{js,ts,mjs}","/root/shipin-cinematic-studio/frontend/app/spa-loading-template.html"]}},
{"blocklist":[],"safelist":[]},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;