/**
 * P4.2.5.2-GATE-01.1 — Customer 360 Path Validation
 *
 * Validates the full Customer 360 lifecycle:
 *   New Customer Event → Identity Resolution → Interaction Link → Timeline → Trace
 *
 * Run: npx tsx tests/gate-01/customer-360-validation.ts
 */

import { prisma } from '../../src/utils/index.js'
import { callbackEventService } from '../../src/enterprise/channel/callback-event.service.js'
import { customerIdentityService } from '../../src/enterprise/channel/customer-identity.service.js'
import { interactionFeedService } from '../../src/enterprise/channel/interaction-feed.service.js'

// Test runner note: Run from backend directory
// npx tsx tests/gate-01/customer-360-validation.ts

// ─── Types ─────────────────────────────────────────────────

interface ValidationCheck {
  name: string
  passed: boolean
  message: string
  details?: Record<string, any>
}

interface ValidationReport {
  gate: string
  timestamp: string
  checks: ValidationCheck[]
  summary: {
    total: number
    passed: number
    failed: number
    passRate: string
  }
}

// ─── Test Data ─────────────────────────────────────────────

const TEST_TENANT_ID = `gate01-test-${Date.now()}`
const TEST_CHANNEL_ACCOUNT_ID = `gate01-account-${Date.now()}`
const TEST_EXTERNAL_USERID = `gate01-wx-user-${Date.now()}`

const MOCK_WECOM_MESSAGE_EVENT = {
  Event: 'text',
  MsgType: 'text',
  UserID: TEST_EXTERNAL_USERID,
  external_userid: TEST_EXTERNAL_USERID,
  content: '你好，我想了解价格',
  CreateTime: Math.floor(Date.now() / 1000),
}

const MOCK_WECOM_CUSTOMER_ADD_EVENT = {
  Event: 'change_external_contact',
  MsgType: 'event',
  UserID: TEST_EXTERNAL_USERID,
  external_userid: TEST_EXTERNAL_USERID,
  CreateTime: Math.floor(Date.now() / 1000),
}

// ─── Validation Runner ─────────────────────────────────────

class Customer360Validator {
  private checks: ValidationCheck[] = []
  private createdIds: string[] = []

  async run(): Promise<ValidationReport> {
    console.log('\n' + '='.repeat(60))
    console.log('  P4.2.5.2-GATE-01.1 — Customer 360 Path Validation')
    console.log('='.repeat(60))

    try {
      // Setup
      await this.setupTestData()

      // Gate 1: New Customer Event
      await this.checkCustomerCreatedEvent()

      // Gate 2: Identity Auto-Generated
      await this.checkIdentityAutoGenerated()

      // Gate 3: Message Linked to Customer
      await this.checkMessageLinkedToCustomer()

      // Gate 4: Timeline Display
      await this.checkTimelineDisplay()

      // Gate 5: Trace Trackable
      await this.checkTraceTrackable()

      // Gate 6: Source Known
      await this.checkSourceKnown()

      // Gate 7: Sync Status
      await this.checkSyncStatus()

    } finally {
      // Cleanup
      await this.cleanup()
    }

    return this.generateReport()
  }

  // ─── Setup ───────────────────────────────────────────────

  private async setupTestData(): Promise<void> {
    console.log('\n📋 Setting up test data...')

    // Create test channel account
    await prisma.enterpriseChannelAccount.create({
      data: {
        id: TEST_CHANNEL_ACCOUNT_ID,
        tenantId: TEST_TENANT_ID,
        channelType: 'wechat_work',
        channelName: 'Gate-01 Test',
        externalAccountId: 'test-corp-id',
        credentialsEncrypted: {
          corpId: 'test-corp-id',
          agentId: 'test-agent-id',
          secret: 'test-secret',
          token: 'test-token',
          encodingAESKey: 'test-aes-key',
        },
        connectionStatus: 'connected',
        connectedAt: new Date(),
      },
    })

    console.log(`   Created channel account: ${TEST_CHANNEL_ACCOUNT_ID}`)
  }

  // ─── Gate 1: New Customer Event ─────────────────────────

  private async checkCustomerCreatedEvent(): Promise<void> {
    console.log('\n🔍 Gate 1: New Customer Event (CUSTOMER_CREATED)')

    try {
      const result = await callbackEventService.processEvent(
        TEST_CHANNEL_ACCOUNT_ID,
        TEST_TENANT_ID,
        MOCK_WECOM_CUSTOMER_ADD_EVENT
      )

      const passed = result.success && result.status === 'processed'
      this.checks.push({
        name: 'new_customer_event',
        passed,
        message: passed ? 'Event processed successfully' : `Failed: ${result.error}`,
        details: { eventId: result.eventId, status: result.status, traceId: result.traceId },
      })

      if (result.eventId) this.createdIds.push(result.eventId)
    } catch (error: any) {
      this.checks.push({
        name: 'new_customer_event',
        passed: false,
        message: `Exception: ${error.message}`,
      })
    }
  }

  // ─── Gate 2: Identity Auto-Generated ─────────────────────

  private async checkIdentityAutoGenerated(): Promise<void> {
    console.log('\n🔍 Gate 2: Identity Auto-Generated (mappingStatus=pending/mapped)')

    try {
      const identity = await customerIdentityService.lookup(
        TEST_TENANT_ID,
        'wechat_work',
        TEST_EXTERNAL_USERID
      )

      const passed = identity !== null &&
        (identity.mappingStatus === 'pending' || identity.mappingStatus === 'mapped')

      this.checks.push({
        name: 'identity_auto_generated',
        passed,
        message: passed
          ? `Identity created with status: ${identity!.mappingStatus}`
          : 'Identity not found or invalid status',
        details: identity ? {
          id: identity.id,
          mappingStatus: identity.mappingStatus,
          displayName: identity.displayName,
          externalId: identity.externalId,
        } : undefined,
      })
    } catch (error: any) {
      this.checks.push({
        name: 'identity_auto_generated',
        passed: false,
        message: `Exception: ${error.message}`,
      })
    }
  }

  // ─── Gate 3: Message Linked to Customer ──────────────────

  private async checkMessageLinkedToCustomer(): Promise<void> {
    console.log('\n🔍 Gate 3: Message Linked to Customer (customerIdentityId not null)')

    // First process a message event
    try {
      const messageResult = await callbackEventService.processEvent(
        TEST_CHANNEL_ACCOUNT_ID,
        TEST_TENANT_ID,
        MOCK_WECOM_MESSAGE_EVENT
      )

      // Check that the interaction has customerIdentityId
      const interactions = await prisma.enterpriseInteraction.findMany({
        where: {
          tenantId: TEST_TENANT_ID,
          externalId: TEST_EXTERNAL_USERID,
        },
        include: { customerIdentity: true },
      })

      const linkedInteraction = interactions.find(ix => ix.customerIdentityId !== null)
      const passed = linkedInteraction !== undefined

      this.checks.push({
        name: 'message_linked_to_customer',
        passed,
        message: passed
          ? `Interaction linked: customerIdentityId=${linkedInteraction!.customerIdentityId}`
          : 'No interaction linked to customer identity',
        details: {
          totalInteractions: interactions.length,
          linkedCount: interactions.filter(ix => ix.customerIdentityId).length,
          messageEventId: messageResult.eventId,
        },
      })
    } catch (error: any) {
      this.checks.push({
        name: 'message_linked_to_customer',
        passed: false,
        message: `Exception: ${error.message}`,
      })
    }
  }

  // ─── Gate 4: Timeline Display ─────────────────────────────

  private async checkTimelineDisplay(): Promise<void> {
    console.log('\n🔍 Gate 4: Timeline Display (sorted by time)')

    try {
      // Get the identity first
      const identity = await customerIdentityService.lookup(
        TEST_TENANT_ID,
        'wechat_work',
        TEST_EXTERNAL_USERID
      )

      if (!identity) {
        this.checks.push({
          name: 'timeline_display',
          passed: false,
          message: 'Cannot test timeline: identity not found (gate 2 failed)',
        })
        return
      }

      const timeline = await interactionFeedService.getCustomerTimeline(
        TEST_TENANT_ID,
        identity.id,
        { limit: 50 }
      )

      const passed = timeline !== null &&
        Array.isArray(timeline.timeline) &&
        timeline.totalInteractions >= 0

      this.checks.push({
        name: 'timeline_display',
        passed,
        message: passed
          ? `Timeline has ${timeline!.timeline.length} date groups, ${timeline!.totalInteractions} total`
          : 'Timeline is null or invalid structure',
        details: timeline ? {
          totalInteractions: timeline.totalInteractions,
          timelineGroups: timeline.timeline.length,
          lastInteractionAt: timeline.lastInteractionAt,
          timelineDates: timeline.timeline.map(t => t.date),
        } : undefined,
      })
    } catch (error: any) {
      this.checks.push({
        name: 'timeline_display',
        passed: false,
        message: `Exception: ${error.message}`,
      })
    }
  }

  // ─── Gate 5: Trace Trackable ──────────────────────────────

  private async checkTraceTrackable(): Promise<void> {
    console.log('\n🔍 Gate 5: Trace Trackable (traceId complete)')

    try {
      // Get trace from ProcessedEvent
      const processedEvent = await prisma.processedEvent.findFirst({
        where: {
          tenantId: TEST_TENANT_ID,
          channelAccountId: TEST_CHANNEL_ACCOUNT_ID,
        },
        orderBy: { processedAt: 'desc' },
      })

      if (!processedEvent) {
        this.checks.push({
          name: 'trace_trackable',
          passed: false,
          message: 'No processed event found',
        })
        return
      }

      // Check trace exists
      const trace = await callbackEventService.getEventTrace(processedEvent.traceId)

      const passed = trace.length > 0 &&
        trace.some(e => e.stage === 'received') &&
        trace.some(e => e.stage === 'processed')

      this.checks.push({
        name: 'trace_trackable',
        passed,
        message: passed
          ? `Trace has ${trace.length} entries covering full pipeline`
          : 'Trace is incomplete',
        details: {
          traceId: processedEvent.traceId,
          stages: trace.map(e => e.stage),
          entryCount: trace.length,
        },
      })
    } catch (error: any) {
      this.checks.push({
        name: 'trace_trackable',
        passed: false,
        message: `Exception: ${error.message}`,
      })
    }
  }

  // ─── Gate 6: Source Known ─────────────────────────────────

  private async checkSourceKnown(): Promise<void> {
    console.log('\n🔍 Gate 6: Source Known (WeCom)')

    try {
      const feedResult = await interactionFeedService.queryFeed({
        tenantId: TEST_TENANT_ID,
        externalId: TEST_EXTERNAL_USERID,
        limit: 10,
      })

      // Verify all interactions come from wechat_work
      const allFromWeCom = feedResult.interactions.length === 0 ||
        feedResult.interactions.every(ix => ix.channel === 'wecom')

      // Also check the envelope
      const envelope = interactionFeedService.envelope(feedResult, 'gate01-trace')
      const envelopeSourceCorrect = envelope.source === 'WeCom'

      const passed = allFromWeCom && envelopeSourceCorrect

      this.checks.push({
        name: 'source_known',
        passed,
        message: passed
          ? `All interactions correctly sourced from WeCom`
          : 'Source attribution incorrect',
        details: {
          interactionCount: feedResult.interactions.length,
          allFromWeCom,
          envelopeSource: envelope.source,
        },
      })
    } catch (error: any) {
      this.checks.push({
        name: 'source_known',
        passed: false,
        message: `Exception: ${error.message}`,
      })
    }
  }

  // ─── Gate 7: Sync Status ──────────────────────────────────

  private async checkSyncStatus(): Promise<void> {
    console.log('\n🔍 Gate 7: Sync Status (synced)')

    try {
      const feedResult = await interactionFeedService.queryFeed({
        tenantId: TEST_TENANT_ID,
        externalId: TEST_EXTERNAL_USERID,
        limit: 10,
      })

      // ProcessedEvent status should be 'success'
      const processedCount = await prisma.processedEvent.count({
        where: {
          tenantId: TEST_TENANT_ID,
          status: 'success',
        },
      })

      const dlqCount = await prisma.deadLetterEvent.count({
        where: {
          tenantId: TEST_TENANT_ID,
        },
      })

      const passed = processedCount > 0 && dlqCount === 0

      this.checks.push({
        name: 'sync_status',
        passed,
        message: passed
          ? `Sync healthy: ${processedCount} processed, ${dlqCount} in DLQ`
          : `Sync issue: ${processedCount} processed, ${dlqCount} in DLQ`,
        details: {
          processedEvents: processedCount,
          dlqEntries: dlqCount,
          interactionsSynced: feedResult.total,
        },
      })
    } catch (error: any) {
      this.checks.push({
        name: 'sync_status',
        passed: false,
        message: `Exception: ${error.message}`,
      })
    }
  }

  // ─── Cleanup ──────────────────────────────────────────────

  private async cleanup(): Promise<void> {
    console.log('\n🧹 Cleaning up test data...')

    try {
      // Delete in reverse dependency order
      await prisma.eventTraceLog.deleteMany({
        where: { tenantId: TEST_TENANT_ID },
      })
      await prisma.deadLetterEvent.deleteMany({
        where: { tenantId: TEST_TENANT_ID },
      })
      await prisma.processedEvent.deleteMany({
        where: { tenantId: TEST_TENANT_ID },
      })
      await prisma.enterpriseInteraction.deleteMany({
        where: { tenantId: TEST_TENANT_ID },
      })
      await prisma.customerIdentity.deleteMany({
        where: { tenantId: TEST_TENANT_ID },
      })
      await prisma.enterpriseChannelAccount.deleteMany({
        where: { id: TEST_CHANNEL_ACCOUNT_ID },
      })

      console.log('   ✅ Test data cleaned up')
    } catch (error: any) {
      console.log(`   ⚠️ Cleanup warning: ${error.message}`)
    }
  }

  // ─── Report Generation ───────────────────────────────────

  private generateReport(): ValidationReport {
    const total = this.checks.length
    const passed = this.checks.filter(c => c.passed).length
    const failed = total - passed
    const passRate = total > 0 ? ((passed / total) * 100).toFixed(1) : '0'

    const report: ValidationReport = {
      gate: 'P4.2.5.2-GATE-01.1',
      timestamp: new Date().toISOString(),
      checks: this.checks,
      summary: { total, passed, failed, passRate },
    }

    // Print summary
    console.log('\n' + '='.repeat(60))
    console.log('  GATE-01.1 VALIDATION REPORT')
    console.log('='.repeat(60))

    for (const check of this.checks) {
      const icon = check.passed ? '✅' : '❌'
      console.log(`  ${icon} ${check.name}: ${check.message}`)
    }

    console.log(`\n  Total: ${total} | ✅ Passed: ${passed} | ❌ Failed: ${failed}`)
    console.log(`  Pass Rate: ${passRate}%`)
    console.log('='.repeat(60))

    //Final verdict
    if (passed === total) {
      console.log('\n  🟢 GATE-01.1 PASS — All checks passed!\n')
    } else if (passed > 0) {
      console.log('\n  🟡 GATE-01.1 PARTIAL — Some checks failed\n')
    } else {
      console.log('\n  🔴 GATE-01.1 FAIL — All checks failed\n')
    }

    return report
  }
}

// ─── Main ──────────────────────────────────────────────────

async function main() {
  const validator = new Customer360Validator()
  const report = await validator.run()

  // Exit with appropriate code
  process.exit(report.summary.failed > 0 ? 1 : 0)
}

main().catch((error) => {
  console.error('Fatal error:', error)
  process.exit(1)
})
