/**
 * Phase 3-B1: Skill Graph Foundation
 * 
 * 53 个核心技能，覆盖 AI/LLM、编程语言、前端、后端、数据、DevOps、产品。
 * 每个技能包含：前置、进阶、互补关系（图结构）。
 * 
 * 数据来源：人工维护（权威）
 * 版本：1.0.0
 */

import type { SkillCanonicalObject } from '../../canonical/schemas'

// ─── 技能ID常量（便于引用） ───

export const SKILL_IDS = {
  // AI / LLM 核心
  ai_fundamentals: 'sco_ai_fundamentals',
  prompt_engineering: 'sco_prompt_engineering',
  langchain: 'sco_langchain',
  langgraph: 'sco_langgraph',
  mcp: 'sco_mcp',
  rag: 'sco_rag',
  agent_design: 'sco_agent_design',
  vector_database: 'sco_vector_database',
  llm_fine_tuning: 'sco_llm_fine_tuning',
  llm_deployment: 'sco_llm_deployment',
  ai_safety: 'sco_ai_safety',
  
  // 编程语言
  python: 'sco_python',
  javascript: 'sco_javascript',
  typescript: 'sco_typescript',
  java: 'sco_java',
  go: 'sco_go',
  rust: 'sco_rust',
  sql: 'sco_sql',
  
  // 前端
  vue: 'sco_vue',
  react: 'sco_react',
  nextjs: 'sco_nextjs',
  nuxt: 'sco_nuxt',
  tailwind: 'sco_tailwind',
  html_css: 'sco_html_css',
  frontend_testing: 'sco_frontend_testing',
  
  // 后端
  nodejs: 'sco_nodejs',
  fastify: 'sco_fastify',
  hono: 'sco_hono',
  express: 'sco_express',
  prisma: 'sco_prisma',
  django: 'sco_django',
  spring_boot: 'sco_spring_boot',
  
  // 数据库
  postgresql: 'sco_postgresql',
  mysql: 'sco_mysql',
  redis: 'sco_redis',
  mongodb: 'sco_mongodb',
  
  // DevOps
  docker: 'sco_docker',
  kubernetes: 'sco_kubernetes',
  ci_cd: 'sco_ci_cd',
  linux: 'sco_linux',
  nginx: 'sco_nginx',
  aws: 'sco_aws',
  
  // 数据分析
  data_analysis: 'sco_data_analysis',
  pandas: 'sco_pandas',
  numpy: 'sco_numpy',
  visualization: 'sco_visualization',
  statistics: 'sco_statistics',
  
  // 产品
  product_thinking: 'sco_product_thinking',
  user_research: 'sco_user_research',
  data_driven: 'sco_data_driven',
  agile: 'sco_agile',
  
  // 软技能
  communication: 'sco_communication',
  teamwork: 'sco_teamwork',
  problem_solving: 'sco_problem_solving',
  creativity: 'sco_creativity',
  execution: 'sco_execution',
  leadership: 'sco_leadership',
} as const

// ─── 53 个核心技能定义 ───

export const CORE_SKILLS: SkillCanonicalObject[] = [
  // ========== AI / LLM 核心 ==========
  {
    id: SKILL_IDS.ai_fundamentals,
    version: '1.0.0',
    name: 'AI 基础',
    aliases: ['人工智能基础', 'AI Fundamentals', '机器学习基础'],
    category: '理论',
    subcategory: 'AI核心',
    description: '理解 AI/ML 基本概念：神经网络、深度学习、Transformer、注意力机制',
    prerequisites: [],
    relatedSkills: [
      { skillId: SKILL_IDS.python, weight: 0.8, type: 'related' },
      { skillId: SKILL_IDS.prompt_engineering, weight: 0.9, type: 'next' },
    ],
    nextSkills: [
      { skillId: SKILL_IDS.prompt_engineering, weight: 1.0, type: 'next' },
      { skillId: SKILL_IDS.langchain, weight: 0.8, type: 'next' },
      { skillId: SKILL_IDS.rag, weight: 0.8, type: 'next' },
    ],
    complementary: [
      { skillId: SKILL_IDS.vector_database, weight: 0.7, type: 'complementary' },
      { skillId: SKILL_IDS.llm_fine_tuning, weight: 0.6, type: 'complementary' },
    ],
    demandLevel: 'critical',
    learningCurve: 3,
    timeToLearn: '4-8周',
    relevantCareers: ['cco_ai_engineer', 'cco_ai_product_manager', 'cco_data_analyst'],
    evidence: [{ type: 'expert', source: '人工维护', date: '2024-01-01', confidence: 0.95 }],
    source: '人工维护',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: SKILL_IDS.prompt_engineering,
    version: '1.0.0',
    name: 'Prompt Engineering',
    aliases: ['提示词工程', 'Prompt Design', '提示工程'],
    category: '工具',
    subcategory: 'AI应用',
    description: '设计和优化 LLM 提示词，掌握 Chain-of-Thought、Few-shot、ReAct 等技术',
    prerequisites: [
      { skillId: SKILL_IDS.ai_fundamentals, weight: 0.9, type: 'prerequisite' },
    ],
    relatedSkills: [
      { skillId: SKILL_IDS.ai_fundamentals, weight: 0.9, type: 'related' },
      { skillId: SKILL_IDS.langchain, weight: 0.8, type: 'related' },
    ],
    nextSkills: [
      { skillId: SKILL_IDS.langchain, weight: 0.9, type: 'next' },
      { skillId: SKILL_IDS.agent_design, weight: 0.8, type: 'next' },
      { skillId: SKILL_IDS.rag, weight: 0.7, type: 'next' },
    ],
    complementary: [
      { skillId: SKILL_IDS.ai_safety, weight: 0.6, type: 'complementary' },
    ],
    demandLevel: 'critical',
    learningCurve: 1,
    timeToLearn: '1-2周',
    relevantCareers: ['cco_ai_engineer', 'cco_ai_product_manager', 'cco_content_editor'],
    evidence: [{ type: 'expert', source: '人工维护', date: '2024-01-01', confidence: 0.95 }],
    source: '人工维护',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: SKILL_IDS.langchain,
    version: '1.0.0',
    name: 'LangChain',
    aliases: ['LangChain.js', 'LangChain Python', 'LangChain 框架'],
    category: '框架',
    subcategory: 'LLM框架',
    description: '使用 LangChain 构建 LLM 应用：Chains、Agents、Memory、Tools',
    prerequisites: [
      { skillId: SKILL_IDS.python, weight: 0.9, type: 'prerequisite' },
      { skillId: SKILL_IDS.prompt_engineering, weight: 0.8, type: 'prerequisite' },
    ],
    relatedSkills: [
      { skillId: SKILL_IDS.prompt_engineering, weight: 0.8, type: 'related' },
      { skillId: SKILL_IDS.rag, weight: 0.9, type: 'related' },
    ],
    nextSkills: [
      { skillId: SKILL_IDS.langgraph, weight: 0.9, type: 'next' },
      { skillId: SKILL_IDS.agent_design, weight: 0.8, type: 'next' },
      { skillId: SKILL_IDS.mcp, weight: 0.7, type: 'next' },
    ],
    complementary: [
      { skillId: SKILL_IDS.vector_database, weight: 0.8, type: 'complementary' },
      { skillId: SKILL_IDS.docker, weight: 0.5, type: 'complementary' },
    ],
    demandLevel: 'high',
    learningCurve: 2,
    timeToLearn: '2-4周',
    relevantCareers: ['cco_ai_engineer', 'cco_backend_engineer'],
    evidence: [{ type: 'expert', source: '人工维护', date: '2024-01-01', confidence: 0.95 }],
    source: '人工维护',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: SKILL_IDS.langgraph,
    version: '1.0.0',
    name: 'LangGraph',
    aliases: ['LangGraph.js', 'LangGraph Python'],
    category: '框架',
    subcategory: 'LLM框架',
    description: '基于图结构的 LLM 应用编排，支持多 Agent 协作、状态管理',
    prerequisites: [
      { skillId: SKILL_IDS.langchain, weight: 0.9, type: 'prerequisite' },
      { skillId: SKILL_IDS.python, weight: 0.8, type: 'prerequisite' },
    ],
    relatedSkills: [
      { skillId: SKILL_IDS.langchain, weight: 0.9, type: 'related' },
      { skillId: SKILL_IDS.agent_design, weight: 0.9, type: 'related' },
    ],
    nextSkills: [
      { skillId: SKILL_IDS.agent_design, weight: 0.9, type: 'next' },
      { skillId: SKILL_IDS.mcp, weight: 0.7, type: 'next' },
    ],
    complementary: [
      { skillId: SKILL_IDS.rag, weight: 0.7, type: 'complementary' },
      { skillId: SKILL_IDS.vector_database, weight: 0.7, type: 'complementary' },
    ],
    demandLevel: 'high',
    learningCurve: 3,
    timeToLearn: '3-5周',
    relevantCareers: ['cco_ai_engineer'],
    evidence: [{ type: 'expert', source: '人工维护', date: '2024-01-01', confidence: 0.9 }],
    source: '人工维护',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: SKILL_IDS.mcp,
    version: '1.0.0',
    name: 'MCP (Model Context Protocol)',
    aliases: ['Model Context Protocol', 'MCP 协议', 'MCP Server'],
    category: '工具',
    subcategory: 'AI协议',
    description: '实现和使用 MCP 协议，让 LLM 安全连接外部工具和数据源',
    prerequisites: [
      { skillId: SKILL_IDS.langchain, weight: 0.7, type: 'prerequisite' },
      { skillId: SKILL_IDS.typescript, weight: 0.6, type: 'prerequisite' },
    ],
    relatedSkills: [
      { skillId: SKILL_IDS.langchain, weight: 0.7, type: 'related' },
      { skillId: SKILL_IDS.agent_design, weight: 0.8, type: 'related' },
    ],
    nextSkills: [
      { skillId: SKILL_IDS.agent_design, weight: 0.8, type: 'next' },
      { skillId: SKILL_IDS.llm_deployment, weight: 0.6, type: 'next' },
    ],
    complementary: [
      { skillId: SKILL_IDS.docker, weight: 0.6, type: 'complementary' },
      { skillId: SKILL_IDS.ai_safety, weight: 0.7, type: 'complementary' },
    ],
    demandLevel: 'high',
    learningCurve: 2,
    timeToLearn: '1-2周',
    relevantCareers: ['cco_ai_engineer'],
    evidence: [{ type: 'expert', source: '人工维护', date: '2024-01-01', confidence: 0.85 }],
    source: '人工维护',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: SKILL_IDS.rag,
    version: '1.0.0',
    name: 'RAG (检索增强生成)',
    aliases: ['Retrieval Augmented Generation', '检索增强', '知识库问答'],
    category: '理论',
    subcategory: 'AI应用',
    description: '构建检索增强生成系统：文档处理、Embedding、向量检索、重排序',
    prerequisites: [
      { skillId: SKILL_IDS.ai_fundamentals, weight: 0.9, type: 'prerequisite' },
      { skillId: SKILL_IDS.vector_database, weight: 0.8, type: 'prerequisite' },
    ],
    relatedSkills: [
      { skillId: SKILL_IDS.vector_database, weight: 0.9, type: 'related' },
      { skillId: SKILL_IDS.langchain, weight: 0.9, type: 'related' },
    ],
    nextSkills: [
      { skillId: SKILL_IDS.agent_design, weight: 0.8, type: 'next' },
      { skillId: SKILL_IDS.llm_fine_tuning, weight: 0.6, type: 'next' },
    ],
    complementary: [
      { skillId: SKILL_IDS.python, weight: 0.8, type: 'complementary' },
      { skillId: SKILL_IDS.postgresql, weight: 0.5, type: 'complementary' },
    ],
    demandLevel: 'critical',
    learningCurve: 3,
    timeToLearn: '3-5周',
    relevantCareers: ['cco_ai_engineer', 'cco_backend_engineer'],
    evidence: [{ type: 'expert', source: '人工维护', date: '2024-01-01', confidence: 0.95 }],
    source: '人工维护',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: SKILL_IDS.agent_design,
    version: '1.0.0',
    name: 'Agent Design',
    aliases: ['AI Agent 设计', '智能体设计', 'Agent 开发'],
    category: '理论',
    subcategory: 'AI应用',
    description: '设计和实现 AI Agent：Planning、Memory、Tool Use、Multi-Agent',
    prerequisites: [
      { skillId: SKILL_IDS.prompt_engineering, weight: 0.8, type: 'prerequisite' },
      { skillId: SKILL_IDS.langchain, weight: 0.8, type: 'prerequisite' },
    ],
    relatedSkills: [
      { skillId: SKILL_IDS.langchain, weight: 0.8, type: 'related' },
      { skillId: SKILL_IDS.langgraph, weight: 0.9, type: 'related' },
      { skillId: SKILL_IDS.mcp, weight: 0.8, type: 'related' },
    ],
    nextSkills: [
      { skillId: SKILL_IDS.llm_deployment, weight: 0.7, type: 'next' },
      { skillId: SKILL_IDS.ai_safety, weight: 0.7, type: 'next' },
    ],
    complementary: [
      { skillId: SKILL_IDS.docker, weight: 0.6, type: 'complementary' },
      { skillId: SKILL_IDS.rag, weight: 0.7, type: 'complementary' },
    ],
    demandLevel: 'critical',
    learningCurve: 4,
    timeToLearn: '4-8周',
    relevantCareers: ['cco_ai_engineer'],
    evidence: [{ type: 'expert', source: '人工维护', date: '2024-01-01', confidence: 0.9 }],
    source: '人工维护',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: SKILL_IDS.vector_database,
    version: '1.0.0',
    name: '向量数据库',
    aliases: ['Vector Database', '向量检索', 'Embedding 存储'],
    category: '工具',
    subcategory: '数据库',
    description: '掌握 Milvus/Qdrant/Pinecone/Chroma 等向量数据库的使用和优化',
    prerequisites: [
      { skillId: SKILL_IDS.python, weight: 0.7, type: 'prerequisite' },
    ],
    relatedSkills: [
      { skillId: SKILL_IDS.rag, weight: 0.9, type: 'related' },
      { skillId: SKILL_IDS.langchain, weight: 0.8, type: 'related' },
    ],
    nextSkills: [
      { skillId: SKILL_IDS.rag, weight: 0.8, type: 'next' },
      { skillId: SKILL_IDS.llm_deployment, weight: 0.6, type: 'next' },
    ],
    complementary: [
      { skillId: SKILL_IDS.postgresql, weight: 0.7, type: 'complementary' },
      { skillId: SKILL_IDS.docker, weight: 0.5, type: 'complementary' },
    ],
    demandLevel: 'high',
    learningCurve: 2,
    timeToLearn: '1-2周',
    relevantCareers: ['cco_ai_engineer', 'cco_backend_engineer'],
    evidence: [{ type: 'expert', source: '人工维护', date: '2024-01-01', confidence: 0.9 }],
    source: '人工维护',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: SKILL_IDS.llm_fine_tuning,
    version: '1.0.0',
    name: 'LLM Fine-tuning',
    aliases: ['大模型微调', '模型微调', 'LoRA', 'QLoRA'],
    category: '理论',
    subcategory: 'AI核心',
    description: '使用 LoRA/QLoRA 等技术对大模型进行微调，适配特定领域任务',
    prerequisites: [
      { skillId: SKILL_IDS.ai_fundamentals, weight: 0.9, type: 'prerequisite' },
      { skillId: SKILL_IDS.python, weight: 0.9, type: 'prerequisite' },
    ],
    relatedSkills: [
      { skillId: SKILL_IDS.ai_fundamentals, weight: 0.9, type: 'related' },
      { skillId: SKILL_IDS.llm_deployment, weight: 0.8, type: 'related' },
    ],
    nextSkills: [
      { skillId: SKILL_IDS.llm_deployment, weight: 0.8, type: 'next' },
    ],
    complementary: [
      { skillId: SKILL_IDS.docker, weight: 0.6, type: 'complementary' },
      { skillId: SKILL_IDS.aws, weight: 0.5, type: 'complementary' },
    ],
    demandLevel: 'high',
    learningCurve: 4,
    timeToLearn: '4-8周',
    relevantCareers: ['cco_ai_engineer', 'cco_ai_algorithm'],
    evidence: [{ type: 'expert', source: '人工维护', date: '2024-01-01', confidence: 0.85 }],
    source: '人工维护',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: SKILL_IDS.llm_deployment,
    version: '1.0.0',
    name: 'LLM 部署与优化',
    aliases: ['大模型部署', 'LLM Serving', '模型推理优化'],
    category: '工具',
    subcategory: 'AI运维',
    description: '使用 vLLM/TGI/Ollama 部署和优化 LLM 推理服务',
    prerequisites: [
      { skillId: SKILL_IDS.llm_fine_tuning, weight: 0.7, type: 'prerequisite' },
      { skillId: SKILL_IDS.docker, weight: 0.8, type: 'prerequisite' },
    ],
    relatedSkills: [
      { skillId: SKILL_IDS.docker, weight: 0.8, type: 'related' },
      { skillId: SKILL_IDS.kubernetes, weight: 0.7, type: 'related' },
    ],
    nextSkills: [],
    complementary: [
      { skillId: SKILL_IDS.aws, weight: 0.7, type: 'complementary' },
      { skillId: SKILL_IDS.linux, weight: 0.8, type: 'complementary' },
    ],
    demandLevel: 'high',
    learningCurve: 4,
    timeToLearn: '3-6周',
    relevantCareers: ['cco_ai_engineer', 'cco_devops'],
    evidence: [{ type: 'expert', source: '人工维护', date: '2024-01-01', confidence: 0.85 }],
    source: '人工维护',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: SKILL_IDS.ai_safety,
    version: '1.0.0',
    name: 'AI Safety & Alignment',
    aliases: ['AI 安全', 'AI 对齐', 'LLM 安全'],
    category: '理论',
    subcategory: 'AI治理',
    description: '理解 AI 安全、对齐、幻觉检测、Prompt Injection 防护',
    prerequisites: [
      { skillId: SKILL_IDS.ai_fundamentals, weight: 0.8, type: 'prerequisite' },
    ],
    relatedSkills: [
      { skillId: SKILL_IDS.agent_design, weight: 0.7, type: 'related' },
      { skillId: SKILL_IDS.prompt_engineering, weight: 0.6, type: 'related' },
    ],
    nextSkills: [],
    complementary: [
      { skillId: SKILL_IDS.mcp, weight: 0.7, type: 'complementary' },
    ],
    demandLevel: 'medium',
    learningCurve: 3,
    timeToLearn: '2-4周',
    relevantCareers: ['cco_ai_engineer', 'cco_ai_product_manager'],
    evidence: [{ type: 'expert', source: '人工维护', date: '2024-01-01', confidence: 0.8 }],
    source: '人工维护',
    updatedAt: '2024-01-01T00:00:00Z',
  },

  // ========== 编程语言 ==========
  {
    id: SKILL_IDS.python,
    version: '1.0.0',
    name: 'Python',
    aliases: ['Python3', 'Python 开发'],
    category: '语言',
    subcategory: '后端语言',
    description: '掌握 Python 编程，包括异步编程、类型提示、常用库',
    prerequisites: [],
    relatedSkills: [
      { skillId: SKILL_IDS.javascript, weight: 0.6, type: 'related' },
    ],
    nextSkills: [
      { skillId: SKILL_IDS.langchain, weight: 0.9, type: 'next' },
      { skillId: SKILL_IDS.django, weight: 0.8, type: 'next' },
      { skillId: SKILL_IDS.data_analysis, weight: 0.8, type: 'next' },
    ],
    complementary: [
      { skillId: SKILL_IDS.sql, weight: 0.7, type: 'complementary' },
      { skillId: SKILL_IDS.docker, weight: 0.5, type: 'complementary' },
    ],
    demandLevel: 'critical',
    learningCurve: 2,
    timeToLearn: '4-8周',
    relevantCareers: ['cco_ai_engineer', 'cco_backend_engineer', 'cco_data_analyst'],
    evidence: [{ type: 'expert', source: '人工维护', date: '2024-01-01', confidence: 0.95 }],
    source: '人工维护',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: SKILL_IDS.javascript,
    version: '1.0.0',
    name: 'JavaScript',
    aliases: ['JS', 'ES6+', 'ECMAScript'],
    category: '语言',
    subcategory: '全栈语言',
    description: '掌握 JavaScript 编程，包括异步编程、DOM、ES6+ 特性',
    prerequisites: [],
    relatedSkills: [
      { skillId: SKILL_IDS.typescript, weight: 0.9, type: 'related' },
    ],
    nextSkills: [
      { skillId: SKILL_IDS.typescript, weight: 0.9, type: 'next' },
      { skillId: SKILL_IDS.react, weight: 0.8, type: 'next' },
      { skillId: SKILL_IDS.vue, weight: 0.8, type: 'next' },
      { skillId: SKILL_IDS.nodejs, weight: 0.8, type: 'next' },
    ],
    complementary: [
      { skillId: SKILL_IDS.html_css, weight: 0.9, type: 'complementary' },
    ],
    demandLevel: 'critical',
    learningCurve: 2,
    timeToLearn: '4-8周',
    relevantCareers: ['cco_frontend_engineer', 'cco_backend_engineer', 'cco_fullstack_engineer'],
    evidence: [{ type: 'expert', source: '人工维护', date: '2024-01-01', confidence: 0.95 }],
    source: '人工维护',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: SKILL_IDS.typescript,
    version: '1.0.0',
    name: 'TypeScript',
    aliases: ['TS', 'TypeScript 开发'],
    category: '语言',
    subcategory: '全栈语言',
    description: '掌握 TypeScript 类型系统、泛型、装饰器等高级特性',
    prerequisites: [
      { skillId: SKILL_IDS.javascript, weight: 0.9, type: 'prerequisite' },
    ],
    relatedSkills: [
      { skillId: SKILL_IDS.javascript, weight: 0.9, type: 'related' },
    ],
    nextSkills: [
      { skillId: SKILL_IDS.react, weight: 0.8, type: 'next' },
      { skillId: SKILL_IDS.vue, weight: 0.8, type: 'next' },
      { skillId: SKILL_IDS.nextjs, weight: 0.8, type: 'next' },
    ],
    complementary: [
      { skillId: SKILL_IDS.nodejs, weight: 0.7, type: 'complementary' },
    ],
    demandLevel: 'critical',
    learningCurve: 2,
    timeToLearn: '2-4周',
    relevantCareers: ['cco_frontend_engineer', 'cco_backend_engineer', 'cco_fullstack_engineer'],
    evidence: [{ type: 'expert', source: '人工维护', date: '2024-01-01', confidence: 0.95 }],
    source: '人工维护',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: SKILL_IDS.java,
    version: '1.0.0',
    name: 'Java',
    aliases: ['Java 开发', 'Java8+', 'Java 17'],
    category: '语言',
    subcategory: '后端语言',
    description: '掌握 Java 编程，包括并发、JVM、Spring 生态',
    prerequisites: [],
    relatedSkills: [
      { skillId: SKILL_IDS.python, weight: 0.5, type: 'related' },
    ],
    nextSkills: [
      { skillId: SKILL_IDS.spring_boot, weight: 0.9, type: 'next' },
    ],
    complementary: [
      { skillId: SKILL_IDS.sql, weight: 0.7, type: 'complementary' },
    ],
    demandLevel: 'high',
    learningCurve: 3,
    timeToLearn: '8-12周',
    relevantCareers: ['cco_backend_engineer'],
    evidence: [{ type: 'expert', source: '人工维护', date: '2024-01-01', confidence: 0.9 }],
    source: '人工维护',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: SKILL_IDS.go,
    version: '1.0.0',
    name: 'Go',
    aliases: ['Golang', 'Go 语言'],
    category: '语言',
    subcategory: '后端语言',
    description: '掌握 Go 编程，包括并发模型、Gin/Echo 框架',
    prerequisites: [],
    relatedSkills: [
      { skillId: SKILL_IDS.python, weight: 0.5, type: 'related' },
    ],
    nextSkills: [],
    complementary: [
      { skillId: SKILL_IDS.docker, weight: 0.7, type: 'complementary' },
      { skillId: SKILL_IDS.kubernetes, weight: 0.7, type: 'complementary' },
    ],
    demandLevel: 'high',
    learningCurve: 2,
    timeToLearn: '4-6周',
    relevantCareers: ['cco_backend_engineer', 'cco_devops'],
    evidence: [{ type: 'expert', source: '人工维护', date: '2024-01-01', confidence: 0.85 }],
    source: '人工维护',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: SKILL_IDS.sql,
    version: '1.0.0',
    name: 'SQL',
    aliases: ['SQL 数据库', '数据库查询', 'MySQL 查询'],
    category: '语言',
    subcategory: '数据库语言',
    description: '掌握 SQL 查询、索引优化、事务、存储过程',
    prerequisites: [],
    relatedSkills: [
      { skillId: SKILL_IDS.postgresql, weight: 0.9, type: 'related' },
      { skillId: SKILL_IDS.mysql, weight: 0.9, type: 'related' },
    ],
    nextSkills: [
      { skillId: SKILL_IDS.postgresql, weight: 0.8, type: 'next' },
      { skillId: SKILL_IDS.mysql, weight: 0.8, type: 'next' },
    ],
    complementary: [
      { skillId: SKILL_IDS.python, weight: 0.7, type: 'complementary' },
    ],
    demandLevel: 'critical',
    learningCurve: 1,
    timeToLearn: '2-4周',
    relevantCareers: ['cco_backend_engineer', 'cco_data_analyst'],
    evidence: [{ type: 'expert', source: '人工维护', date: '2024-01-01', confidence: 0.95 }],
    source: '人工维护',
    updatedAt: '2024-01-01T00:00:00Z',
  },

  // ========== 前端框架 ==========
  {
    id: SKILL_IDS.vue,
    version: '1.0.0',
    name: 'Vue.js',
    aliases: ['Vue', 'Vue3', 'Vue 3'],
    category: '框架',
    subcategory: '前端框架',
    description: '掌握 Vue 3 开发：Composition API、Pinia、Vue Router',
    prerequisites: [
      { skillId: SKILL_IDS.javascript, weight: 0.9, type: 'prerequisite' },
      { skillId: SKILL_IDS.html_css, weight: 0.8, type: 'prerequisite' },
    ],
    relatedSkills: [
      { skillId: SKILL_IDS.react, weight: 0.7, type: 'related' },
    ],
    nextSkills: [
      { skillId: SKILL_IDS.nuxt, weight: 0.9, type: 'next' },
      { skillId: SKILL_IDS.typescript, weight: 0.7, type: 'next' },
    ],
    complementary: [
      { skillId: SKILL_IDS.tailwind, weight: 0.8, type: 'complementary' },
    ],
    demandLevel: 'high',
    learningCurve: 2,
    timeToLearn: '3-5周',
    relevantCareers: ['cco_frontend_engineer', 'cco_fullstack_engineer'],
    evidence: [{ type: 'expert', source: '人工维护', date: '2024-01-01', confidence: 0.95 }],
    source: '人工维护',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: SKILL_IDS.react,
    version: '1.0.0',
    name: 'React',
    aliases: ['React.js', 'React 18', 'React 开发'],
    category: '框架',
    subcategory: '前端框架',
    description: '掌握 React 开发：Hooks、状态管理、性能优化',
    prerequisites: [
      { skillId: SKILL_IDS.javascript, weight: 0.9, type: 'prerequisite' },
      { skillId: SKILL_IDS.html_css, weight: 0.8, type: 'prerequisite' },
    ],
    relatedSkills: [
      { skillId: SKILL_IDS.vue, weight: 0.7, type: 'related' },
    ],
    nextSkills: [
      { skillId: SKILL_IDS.nextjs, weight: 0.9, type: 'next' },
      { skillId: SKILL_IDS.typescript, weight: 0.7, type: 'next' },
    ],
    complementary: [
      { skillId: SKILL_IDS.tailwind, weight: 0.8, type: 'complementary' },
    ],
    demandLevel: 'critical',
    learningCurve: 2,
    timeToLearn: '3-5周',
    relevantCareers: ['cco_frontend_engineer', 'cco_fullstack_engineer'],
    evidence: [{ type: 'expert', source: '人工维护', date: '2024-01-01', confidence: 0.95 }],
    source: '人工维护',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: SKILL_IDS.nextjs,
    version: '1.0.0',
    name: 'Next.js',
    aliases: ['Next.js', 'Nextjs', 'Next 14'],
    category: '框架',
    subcategory: '全栈框架',
    description: '掌握 Next.js 开发：SSR/SSG、App Router、Server Components',
    prerequisites: [
      { skillId: SKILL_IDS.react, weight: 0.9, type: 'prerequisite' },
      { skillId: SKILL_IDS.typescript, weight: 0.7, type: 'prerequisite' },
    ],
    relatedSkills: [
      { skillId: SKILL_IDS.react, weight: 0.9, type: 'related' },
    ],
    nextSkills: [],
    complementary: [
      { skillId: SKILL_IDS.tailwind, weight: 0.8, type: 'complementary' },
      { skillId: SKILL_IDS.aws, weight: 0.5, type: 'complementary' },
    ],
    demandLevel: 'high',
    learningCurve: 3,
    timeToLearn: '3-5周',
    relevantCareers: ['cco_frontend_engineer', 'cco_fullstack_engineer'],
    evidence: [{ type: 'expert', source: '人工维护', date: '2024-01-01', confidence: 0.9 }],
    source: '人工维护',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: SKILL_IDS.nuxt,
    version: '1.0.0',
    name: 'Nuxt',
    aliases: ['Nuxt.js', 'Nuxt 3', 'Nuxt 开发'],
    category: '框架',
    subcategory: '全栈框架',
    description: '掌握 Nuxt 3 开发：SSR/SSG、Nitro、组合式 API',
    prerequisites: [
      { skillId: SKILL_IDS.vue, weight: 0.9, type: 'prerequisite' },
      { skillId: SKILL_IDS.typescript, weight: 0.7, type: 'prerequisite' },
    ],
    relatedSkills: [
      { skillId: SKILL_IDS.vue, weight: 0.9, type: 'related' },
    ],
    nextSkills: [],
    complementary: [
      { skillId: SKILL_IDS.tailwind, weight: 0.8, type: 'complementary' },
    ],
    demandLevel: 'medium',
    learningCurve: 2,
    timeToLearn: '2-4周',
    relevantCareers: ['cco_frontend_engineer', 'cco_fullstack_engineer'],
    evidence: [{ type: 'expert', source: '人工维护', date: '2024-01-01', confidence: 0.85 }],
    source: '人工维护',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: SKILL_IDS.tailwind,
    version: '1.0.0',
    name: 'Tailwind CSS',
    aliases: ['Tailwind', 'TailwindCSS', '原子化 CSS'],
    category: '工具',
    subcategory: 'CSS框架',
    description: '使用 Tailwind CSS 快速构建响应式 UI',
    prerequisites: [
      { skillId: SKILL_IDS.html_css, weight: 0.8, type: 'prerequisite' },
    ],
    relatedSkills: [
      { skillId: SKILL_IDS.html_css, weight: 0.8, type: 'related' },
    ],
    nextSkills: [],
    complementary: [
      { skillId: SKILL_IDS.react, weight: 0.8, type: 'complementary' },
      { skillId: SKILL_IDS.vue, weight: 0.8, type: 'complementary' },
    ],
    demandLevel: 'high',
    learningCurve: 1,
    timeToLearn: '1-2周',
    relevantCareers: ['cco_frontend_engineer'],
    evidence: [{ type: 'expert', source: '人工维护', date: '2024-01-01', confidence: 0.95 }],
    source: '人工维护',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: SKILL_IDS.html_css,
    version: '1.0.0',
    name: 'HTML/CSS',
    aliases: ['HTML', 'CSS', 'HTML5', 'CSS3', '网页基础'],
    category: '语言',
    subcategory: '标记语言',
    description: '掌握 HTML5 语义化标签和 CSS3 布局（Flexbox、Grid）',
    prerequisites: [],
    relatedSkills: [],
    nextSkills: [
      { skillId: SKILL_IDS.javascript, weight: 0.9, type: 'next' },
      { skillId: SKILL_IDS.tailwind, weight: 0.8, type: 'next' },
    ],
    complementary: [],
    demandLevel: 'critical',
    learningCurve: 1,
    timeToLearn: '2-4周',
    relevantCareers: ['cco_frontend_engineer'],
    evidence: [{ type: 'expert', source: '人工维护', date: '2024-01-01', confidence: 0.95 }],
    source: '人工维护',
    updatedAt: '2024-01-01T00:00:00Z',
  },

  // ========== 后端 ==========
  {
    id: SKILL_IDS.nodejs,
    version: '1.0.0',
    name: 'Node.js',
    aliases: ['Node', 'Nodejs', 'Node.js 开发'],
    category: '框架',
    subcategory: '后端运行时',
    description: '掌握 Node.js 开发：Event Loop、Stream、模块系统',
    prerequisites: [
      { skillId: SKILL_IDS.javascript, weight: 0.9, type: 'prerequisite' },
    ],
    relatedSkills: [
      { skillId: SKILL_IDS.javascript, weight: 0.9, type: 'related' },
    ],
    nextSkills: [
      { skillId: SKILL_IDS.fastify, weight: 0.8, type: 'next' },
      { skillId: SKILL_IDS.express, weight: 0.8, type: 'next' },
      { skillId: SKILL_IDS.prisma, weight: 0.7, type: 'next' },
    ],
    complementary: [
      { skillId: SKILL_IDS.postgresql, weight: 0.7, type: 'complementary' },
      { skillId: SKILL_IDS.redis, weight: 0.6, type: 'complementary' },
    ],
    demandLevel: 'critical',
    learningCurve: 2,
    timeToLearn: '3-5周',
    relevantCareers: ['cco_backend_engineer', 'cco_fullstack_engineer'],
    evidence: [{ type: 'expert', source: '人工维护', date: '2024-01-01', confidence: 0.95 }],
    source: '人工维护',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: SKILL_IDS.fastify,
    version: '1.0.0',
    name: 'Fastify',
    aliases: ['Fastify.js', 'Fastify 框架'],
    category: '框架',
    subcategory: '后端框架',
    description: '使用 Fastify 构建高性能 Web 服务，支持插件系统和 TypeBox',
    prerequisites: [
      { skillId: SKILL_IDS.nodejs, weight: 0.9, type: 'prerequisite' },
      { skillId: SKILL_IDS.typescript, weight: 0.7, type: 'prerequisite' },
    ],
    relatedSkills: [
      { skillId: SKILL_IDS.nodejs, weight: 0.9, type: 'related' },
    ],
    nextSkills: [
      { skillId: SKILL_IDS.prisma, weight: 0.7, type: 'next' },
    ],
    complementary: [
      { skillId: SKILL_IDS.postgresql, weight: 0.7, type: 'complementary' },
    ],
    demandLevel: 'medium',
    learningCurve: 2,
    timeToLearn: '1-2周',
    relevantCareers: ['cco_backend_engineer'],
    evidence: [{ type: 'expert', source: '人工维护', date: '2024-01-01', confidence: 0.85 }],
    source: '人工维护',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: SKILL_IDS.express,
    version: '1.0.0',
    name: 'Express.js',
    aliases: ['Express', 'Express 框架'],
    category: '框架',
    subcategory: '后端框架',
    description: '使用 Express 构建 Web 服务和 RESTful API',
    prerequisites: [
      { skillId: SKILL_IDS.nodejs, weight: 0.9, type: 'prerequisite' },
    ],
    relatedSkills: [
      { skillId: SKILL_IDS.nodejs, weight: 0.9, type: 'related' },
    ],
    nextSkills: [],
    complementary: [
      { skillId: SKILL_IDS.postgresql, weight: 0.7, type: 'complementary' },
    ],
    demandLevel: 'high',
    learningCurve: 1,
    timeToLearn: '1-2周',
    relevantCareers: ['cco_backend_engineer'],
    evidence: [{ type: 'expert', source: '人工维护', date: '2024-01-01', confidence: 0.9 }],
    source: '人工维护',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: SKILL_IDS.prisma,
    version: '1.0.0',
    name: 'Prisma',
    aliases: ['Prisma ORM', 'Prisma 数据库'],
    category: '工具',
    subcategory: 'ORM',
    description: '使用 Prisma 进行类型安全的数据库操作',
    prerequisites: [
      { skillId: SKILL_IDS.nodejs, weight: 0.8, type: 'prerequisite' },
      { skillId: SKILL_IDS.typescript, weight: 0.8, type: 'prerequisite' },
    ],
    relatedSkills: [
      { skillId: SKILL_IDS.nodejs, weight: 0.8, type: 'related' },
    ],
    nextSkills: [],
    complementary: [
      { skillId: SKILL_IDS.postgresql, weight: 0.9, type: 'complementary' },
    ],
    demandLevel: 'medium',
    learningCurve: 2,
    timeToLearn: '1-2周',
    relevantCareers: ['cco_backend_engineer', 'cco_fullstack_engineer'],
    evidence: [{ type: 'expert', source: '人工维护', date: '2024-01-01', confidence: 0.85 }],
    source: '人工维护',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: SKILL_IDS.django,
    version: '1.0.0',
    name: 'Django',
    aliases: ['Django Framework', 'Django 框架'],
    category: '框架',
    subcategory: '后端框架',
    description: '使用 Django 快速构建 Web 应用，掌握 ORM、Admin、DRF',
    prerequisites: [
      { skillId: SKILL_IDS.python, weight: 0.9, type: 'prerequisite' },
    ],
    relatedSkills: [
      { skillId: SKILL_IDS.python, weight: 0.9, type: 'related' },
    ],
    nextSkills: [],
    complementary: [
      { skillId: SKILL_IDS.postgresql, weight: 0.7, type: 'complementary' },
    ],
    demandLevel: 'medium',
    learningCurve: 2,
    timeToLearn: '3-5周',
    relevantCareers: ['cco_backend_engineer'],
    evidence: [{ type: 'expert', source: '人工维护', date: '2024-01-01', confidence: 0.85 }],
    source: '人工维护',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: SKILL_IDS.spring_boot,
    version: '1.0.0',
    name: 'Spring Boot',
    aliases: ['Spring', 'SpringBoot', 'Spring 框架'],
    category: '框架',
    subcategory: '后端框架',
    description: '使用 Spring Boot 构建企业级 Java 应用',
    prerequisites: [
      { skillId: SKILL_IDS.java, weight: 0.9, type: 'prerequisite' },
    ],
    relatedSkills: [
      { skillId: SKILL_IDS.java, weight: 0.9, type: 'related' },
    ],
    nextSkills: [],
    complementary: [
      { skillId: SKILL_IDS.mysql, weight: 0.7, type: 'complementary' },
    ],
    demandLevel: 'high',
    learningCurve: 3,
    timeToLearn: '4-8周',
    relevantCareers: ['cco_backend_engineer'],
    evidence: [{ type: 'expert', source: '人工维护', date: '2024-01-01', confidence: 0.9 }],
    source: '人工维护',
    updatedAt: '2024-01-01T00:00:00Z',
  },

  // ========== 数据库 ==========
  {
    id: SKILL_IDS.postgresql,
    version: '1.0.0',
    name: 'PostgreSQL',
    aliases: ['Postgres', 'PG', 'PostgreSQL 数据库'],
    category: '工具',
    subcategory: '关系型数据库',
    description: '掌握 PostgreSQL：索引、事务、JSONB、全文检索',
    prerequisites: [
      { skillId: SKILL_IDS.sql, weight: 0.9, type: 'prerequisite' },
    ],
    relatedSkills: [
      { skillId: SKILL_IDS.sql, weight: 0.9, type: 'related' },
    ],
    nextSkills: [],
    complementary: [
      { skillId: SKILL_IDS.prisma, weight: 0.7, type: 'complementary' },
      { skillId: SKILL_IDS.redis, weight: 0.6, type: 'complementary' },
    ],
    demandLevel: 'high',
    learningCurve: 2,
    timeToLearn: '2-4周',
    relevantCareers: ['cco_backend_engineer', 'cco_data_analyst'],
    evidence: [{ type: 'expert', source: '人工维护', date: '2024-01-01', confidence: 0.95 }],
    source: '人工维护',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: SKILL_IDS.mysql,
    version: '1.0.0',
    name: 'MySQL',
    aliases: ['MySQL 数据库', 'MySQL 开发'],
    category: '工具',
    subcategory: '关系型数据库',
    description: '掌握 MySQL：索引优化、事务隔离、主从复制',
    prerequisites: [
      { skillId: SKILL_IDS.sql, weight: 0.9, type: 'prerequisite' },
    ],
    relatedSkills: [
      { skillId: SKILL_IDS.sql, weight: 0.9, type: 'related' },
    ],
    nextSkills: [],
    complementary: [
      { skillId: SKILL_IDS.spring_boot, weight: 0.7, type: 'complementary' },
    ],
    demandLevel: 'high',
    learningCurve: 2,
    timeToLearn: '2-4周',
    relevantCareers: ['cco_backend_engineer'],
    evidence: [{ type: 'expert', source: '人工维护', date: '2024-01-01', confidence: 0.95 }],
    source: '人工维护',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: SKILL_IDS.redis,
    version: '1.0.0',
    name: 'Redis',
    aliases: ['Redis 缓存', 'Redis 数据库'],
    category: '工具',
    subcategory: '缓存数据库',
    description: '掌握 Redis：数据结构、持久化、集群、缓存策略',
    prerequisites: [],
    relatedSkills: [],
    nextSkills: [],
    complementary: [
      { skillId: SKILL_IDS.nodejs, weight: 0.6, type: 'complementary' },
      { skillId: SKILL_IDS.postgresql, weight: 0.6, type: 'complementary' },
    ],
    demandLevel: 'high',
    learningCurve: 2,
    timeToLearn: '1-2周',
    relevantCareers: ['cco_backend_engineer', 'cco_devops'],
    evidence: [{ type: 'expert', source: '人工维护', date: '2024-01-01', confidence: 0.9 }],
    source: '人工维护',
    updatedAt: '2024-01-01T00:00:00Z',
  },

  // ========== DevOps ==========
  {
    id: SKILL_IDS.docker,
    version: '1.0.0',
    name: 'Docker',
    aliases: ['Docker 容器', '容器化', 'Docker 开发'],
    category: '工具',
    subcategory: '容器化',
    description: '掌握 Docker：镜像构建、容器编排、多阶段构建',
    prerequisites: [
      { skillId: SKILL_IDS.linux, weight: 0.7, type: 'prerequisite' },
    ],
    relatedSkills: [
      { skillId: SKILL_IDS.linux, weight: 0.7, type: 'related' },
    ],
    nextSkills: [
      { skillId: SKILL_IDS.kubernetes, weight: 0.8, type: 'next' },
      { skillId: SKILL_IDS.ci_cd, weight: 0.7, type: 'next' },
    ],
    complementary: [
      { skillId: SKILL_IDS.nodejs, weight: 0.5, type: 'complementary' },
    ],
    demandLevel: 'critical',
    learningCurve: 2,
    timeToLearn: '2-3周',
    relevantCareers: ['cco_devops', 'cco_backend_engineer'],
    evidence: [{ type: 'expert', source: '人工维护', date: '2024-01-01', confidence: 0.95 }],
    source: '人工维护',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: SKILL_IDS.kubernetes,
    version: '1.0.0',
    name: 'Kubernetes',
    aliases: ['K8s', 'K8s 集群', '容器编排'],
    category: '工具',
    subcategory: '容器编排',
    description: '掌握 Kubernetes：Pod/Deployment/Service/HPA、Helm',
    prerequisites: [
      { skillId: SKILL_IDS.docker, weight: 0.9, type: 'prerequisite' },
    ],
    relatedSkills: [
      { skillId: SKILL_IDS.docker, weight: 0.9, type: 'related' },
    ],
    nextSkills: [],
    complementary: [
      { skillId: SKILL_IDS.aws, weight: 0.7, type: 'complementary' },
    ],
    demandLevel: 'high',
    learningCurve: 4,
    timeToLearn: '4-8周',
    relevantCareers: ['cco_devops'],
    evidence: [{ type: 'expert', source: '人工维护', date: '2024-01-01', confidence: 0.85 }],
    source: '人工维护',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: SKILL_IDS.ci_cd,
    version: '1.0.0',
    name: 'CI/CD',
    aliases: ['持续集成', '持续部署', 'CI/CD Pipeline'],
    category: '工具',
    subcategory: 'DevOps',
    description: '搭建 CI/CD 流水线：GitHub Actions、GitLab CI、Jenkins',
    prerequisites: [
      { skillId: SKILL_IDS.docker, weight: 0.7, type: 'prerequisite' },
    ],
    relatedSkills: [
      { skillId: SKILL_IDS.docker, weight: 0.7, type: 'related' },
    ],
    nextSkills: [],
    complementary: [
      { skillId: SKILL_IDS.linux, weight: 0.6, type: 'complementary' },
    ],
    demandLevel: 'high',
    learningCurve: 2,
    timeToLearn: '2-4周',
    relevantCareers: ['cco_devops'],
    evidence: [{ type: 'expert', source: '人工维护', date: '2024-01-01', confidence: 0.85 }],
    source: '人工维护',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: SKILL_IDS.linux,
    version: '1.0.0',
    name: 'Linux',
    aliases: ['Linux 系统', 'Linux 运维', 'Linux 基础'],
    category: '工具',
    subcategory: '操作系统',
    description: '掌握 Linux 系统：Shell、文件系统、进程管理、网络配置',
    prerequisites: [],
    relatedSkills: [],
    nextSkills: [
      { skillId: SKILL_IDS.docker, weight: 0.8, type: 'next' },
      { skillId: SKILL_IDS.nginx, weight: 0.7, type: 'next' },
    ],
    complementary: [],
    demandLevel: 'high',
    learningCurve: 2,
    timeToLearn: '3-6周',
    relevantCareers: ['cco_devops', 'cco_backend_engineer'],
    evidence: [{ type: 'expert', source: '人工维护', date: '2024-01-01', confidence: 0.9 }],
    source: '人工维护',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: SKILL_IDS.nginx,
    version: '1.0.0',
    name: 'Nginx',
    aliases: ['Nginx 配置', 'Nginx 反向代理', 'Web 服务器'],
    category: '工具',
    subcategory: 'Web服务器',
    description: '掌握 Nginx：反向代理、负载均衡、HTTPS 配置',
    prerequisites: [
      { skillId: SKILL_IDS.linux, weight: 0.7, type: 'prerequisite' },
    ],
    relatedSkills: [
      { skillId: SKILL_IDS.linux, weight: 0.7, type: 'related' },
    ],
    nextSkills: [],
    complementary: [],
    demandLevel: 'high',
    learningCurve: 1,
    timeToLearn: '1-2周',
    relevantCareers: ['cco_devops', 'cco_backend_engineer'],
    evidence: [{ type: 'expert', source: '人工维护', date: '2024-01-01', confidence: 0.85 }],
    source: '人工维护',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: SKILL_IDS.aws,
    version: '1.0.0',
    name: 'AWS',
    aliases: ['Amazon Web Services', 'AWS 云服务', '亚马逊云'],
    category: '工具',
    subcategory: '云平台',
    description: '掌握 AWS 核心服务：EC2/S3/Lambda/RDS/CloudFront',
    prerequisites: [],
    relatedSkills: [],
    nextSkills: [],
    complementary: [
      { skillId: SKILL_IDS.docker, weight: 0.6, type: 'complementary' },
      { skillId: SKILL_IDS.kubernetes, weight: 0.7, type: 'complementary' },
    ],
    demandLevel: 'high',
    learningCurve: 3,
    timeToLearn: '4-8周',
    relevantCareers: ['cco_devops', 'cco_backend_engineer'],
    evidence: [{ type: 'expert', source: '人工维护', date: '2024-01-01', confidence: 0.85 }],
    source: '人工维护',
    updatedAt: '2024-01-01T00:00:00Z',
  },

  // ========== 数据分析 ==========
  {
    id: SKILL_IDS.data_analysis,
    version: '1.0.0',
    name: '数据分析',
    aliases: ['Data Analysis', '业务数据分析', '数据分析方法'],
    category: '理论',
    subcategory: '数据科学',
    description: '掌握数据分析方法：描述性统计、推断性统计、A/B 测试',
    prerequisites: [
      { skillId: SKILL_IDS.statistics, weight: 0.8, type: 'prerequisite' },
    ],
    relatedSkills: [
      { skillId: SKILL_IDS.python, weight: 0.8, type: 'related' },
      { skillId: SKILL_IDS.pandas, weight: 0.9, type: 'related' },
    ],
    nextSkills: [
      { skillId: SKILL_IDS.pandas, weight: 0.8, type: 'next' },
      { skillId: SKILL_IDS.visualization, weight: 0.8, type: 'next' },
    ],
    complementary: [
      { skillId: SKILL_IDS.sql, weight: 0.8, type: 'complementary' },
    ],
    demandLevel: 'high',
    learningCurve: 2,
    timeToLearn: '3-5周',
    relevantCareers: ['cco_data_analyst'],
    evidence: [{ type: 'expert', source: '人工维护', date: '2024-01-01', confidence: 0.9 }],
    source: '人工维护',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: SKILL_IDS.pandas,
    version: '1.0.0',
    name: 'Pandas',
    aliases: ['Pandas 库', 'Python Pandas', '数据处理'],
    category: '工具',
    subcategory: '数据处理',
    description: '使用 Pandas 进行数据清洗、转换、分析',
    prerequisites: [
      { skillId: SKILL_IDS.python, weight: 0.9, type: 'prerequisite' },
    ],
    relatedSkills: [
      { skillId: SKILL_IDS.python, weight: 0.9, type: 'related' },
    ],
    nextSkills: [
      { skillId: SKILL_IDS.data_analysis, weight: 0.8, type: 'next' },
    ],
    complementary: [
      { skillId: SKILL_IDS.numpy, weight: 0.8, type: 'complementary' },
    ],
    demandLevel: 'high',
    learningCurve: 2,
    timeToLearn: '2-3周',
    relevantCareers: ['cco_data_analyst'],
    evidence: [{ type: 'expert', source: '人工维护', date: '2024-01-01', confidence: 0.9 }],
    source: '人工维护',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: SKILL_IDS.numpy,
    version: '1.0.0',
    name: 'NumPy',
    aliases: ['NumPy 库', 'Python NumPy', '数值计算'],
    category: '工具',
    subcategory: '数值计算',
    description: '使用 NumPy 进行数值计算、矩阵运算',
    prerequisites: [
      { skillId: SKILL_IDS.python, weight: 0.9, type: 'prerequisite' },
    ],
    relatedSkills: [
      { skillId: SKILL_IDS.python, weight: 0.9, type: 'related' },
    ],
    nextSkills: [
      { skillId: SKILL_IDS.pandas, weight: 0.8, type: 'next' },
    ],
    complementary: [],
    demandLevel: 'medium',
    learningCurve: 2,
    timeToLearn: '1-2周',
    relevantCareers: ['cco_data_analyst', 'cco_ai_engineer'],
    evidence: [{ type: 'expert', source: '人工维护', date: '2024-01-01', confidence: 0.85 }],
    source: '人工维护',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: SKILL_IDS.visualization,
    version: '1.0.0',
    name: '数据可视化',
    aliases: ['Data Visualization', '可视化', '图表'],
    category: '工具',
    subcategory: '可视化',
    description: '使用 Matplotlib/ECharts/D3.js 进行数据可视化',
    prerequisites: [],
    relatedSkills: [],
    nextSkills: [],
    complementary: [
      { skillId: SKILL_IDS.python, weight: 0.7, type: 'complementary' },
      { skillId: SKILL_IDS.data_analysis, weight: 0.8, type: 'complementary' },
    ],
    demandLevel: 'medium',
    learningCurve: 1,
    timeToLearn: '1-2周',
    relevantCareers: ['cco_data_analyst'],
    evidence: [{ type: 'expert', source: '人工维护', date: '2024-01-01', confidence: 0.85 }],
    source: '人工维护',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: SKILL_IDS.statistics,
    version: '1.0.0',
    name: '统计学',
    aliases: ['Statistics', '数理统计', '应用统计'],
    category: '理论',
    subcategory: '数学',
    description: '掌握统计学基础：概率、假设检验、回归分析',
    prerequisites: [],
    relatedSkills: [],
    nextSkills: [
      { skillId: SKILL_IDS.data_analysis, weight: 0.9, type: 'next' },
    ],
    complementary: [],
    demandLevel: 'high',
    learningCurve: 3,
    timeToLearn: '4-6周',
    relevantCareers: ['cco_data_analyst'],
    evidence: [{ type: 'expert', source: '人工维护', date: '2024-01-01', confidence: 0.9 }],
    source: '人工维护',
    updatedAt: '2024-01-01T00:00:00Z',
  },

  // ========== 产品 ==========
  {
    id: SKILL_IDS.product_thinking,
    version: '1.0.0',
    name: '产品思维',
    aliases: ['产品sense', '产品感觉', 'Product Thinking'],
    category: '软技能',
    subcategory: '产品',
    description: '培养产品思维：用户价值、商业逻辑、优先级判断',
    prerequisites: [],
    relatedSkills: [],
    nextSkills: [
      { skillId: SKILL_IDS.user_research, weight: 0.8, type: 'next' },
    ],
    complementary: [
      { skillId: SKILL_IDS.data_driven, weight: 0.7, type: 'complementary' },
    ],
    demandLevel: 'high',
    learningCurve: 2,
    timeToLearn: '持续学习',
    relevantCareers: ['cco_ai_product_manager', 'cco_product_manager'],
    evidence: [{ type: 'expert', source: '人工维护', date: '2024-01-01', confidence: 0.85 }],
    source: '人工维护',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: SKILL_IDS.user_research,
    version: '1.0.0',
    name: '用户研究',
    aliases: ['User Research', '用研', '用户调研'],
    category: '软技能',
    subcategory: '产品',
    description: '掌握用户研究方法：访谈、问卷、可用性测试、数据分析',
    prerequisites: [],
    relatedSkills: [],
    nextSkills: [],
    complementary: [
      { skillId: SKILL_IDS.product_thinking, weight: 0.8, type: 'complementary' },
    ],
    demandLevel: 'medium',
    learningCurve: 2,
    timeToLearn: '2-4周',
    relevantCareers: ['cco_ai_product_manager', 'cco_product_manager'],
    evidence: [{ type: 'expert', source: '人工维护', date: '2024-01-01', confidence: 0.8 }],
    source: '人工维护',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: SKILL_IDS.data_driven,
    version: '1.0.0',
    name: '数据驱动决策',
    aliases: ['Data Driven', '数据决策', '用数据说话'],
    category: '软技能',
    subcategory: '产品',
    description: '基于数据做产品决策：指标设计、A/B 测试、归因分析',
    prerequisites: [],
    relatedSkills: [],
    nextSkills: [],
    complementary: [
      { skillId: SKILL_IDS.product_thinking, weight: 0.7, type: 'complementary' },
      { skillId: SKILL_IDS.data_analysis, weight: 0.8, type: 'complementary' },
    ],
    demandLevel: 'high',
    learningCurve: 2,
    timeToLearn: '2-4周',
    relevantCareers: ['cco_ai_product_manager', 'cco_product_manager'],
    evidence: [{ type: 'expert', source: '人工维护', date: '2024-01-01', confidence: 0.85 }],
    source: '人工维护',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: SKILL_IDS.agile,
    version: '1.0.0',
    name: '敏捷开发',
    aliases: ['Agile', 'Scrum', '敏捷', '敏捷方法论'],
    category: '软技能',
    subcategory: '研发管理',
    description: '掌握敏捷开发方法：Scrum、Kanban、迭代管理',
    prerequisites: [],
    relatedSkills: [],
    nextSkills: [],
    complementary: [
      { skillId: SKILL_IDS.teamwork, weight: 0.7, type: 'complementary' },
    ],
    demandLevel: 'high',
    learningCurve: 1,
    timeToLearn: '1-2周',
    relevantCareers: ['cco_product_manager', 'cco_devops'],
    evidence: [{ type: 'expert', source: '人工维护', date: '2024-01-01', confidence: 0.85 }],
    source: '人工维护',
    updatedAt: '2024-01-01T00:00:00Z',
  },

  // ========== 软技能 ==========
  {
    id: SKILL_IDS.communication,
    version: '1.0.0',
    name: '沟通表达',
    aliases: ['沟通', '表达能力', 'Communication'],
    category: '软技能',
    subcategory: '通用',
    description: '有效沟通：清晰表达、积极倾听、反馈技巧',
    prerequisites: [],
    relatedSkills: [],
    nextSkills: [],
    complementary: [],
    demandLevel: 'high',
    learningCurve: 1,
    timeToLearn: '持续练习',
    relevantCareers: [],
    evidence: [{ type: 'expert', source: '人工维护', date: '2024-01-01', confidence: 0.8 }],
    source: '人工维护',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: SKILL_IDS.teamwork,
    version: '1.0.0',
    name: '团队协作',
    aliases: ['团队合作', 'Teamwork', '协作能力'],
    category: '软技能',
    subcategory: '通用',
    description: '高效团队协作：跨部门合作、冲突管理、共享目标',
    prerequisites: [],
    relatedSkills: [],
    nextSkills: [],
    complementary: [],
    demandLevel: 'high',
    learningCurve: 1,
    timeToLearn: '持续练习',
    relevantCareers: [],
    evidence: [{ type: 'expert', source: '人工维护', date: '2024-01-01', confidence: 0.8 }],
    source: '人工维护',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: SKILL_IDS.problem_solving,
    version: '1.0.0',
    name: '问题解决',
    aliases: ['Problem Solving', '解决问题', '分析问题'],
    category: '软技能',
    subcategory: '通用',
    description: '结构化问题解决：定义问题、分解、方案评估、执行',
    prerequisites: [],
    relatedSkills: [],
    nextSkills: [],
    complementary: [],
    demandLevel: 'high',
    learningCurve: 2,
    timeToLearn: '持续练习',
    relevantCareers: [],
    evidence: [{ type: 'expert', source: '人工维护', date: '2024-01-01', confidence: 0.8 }],
    source: '人工维护',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: SKILL_IDS.creativity,
    version: '1.0.0',
    name: '创造力',
    aliases: ['创意', 'Creativity', '创新能力', 'Creative Thinking'],
    category: '软技能',
    subcategory: '通用',
    description: '创造性思维：发散思维、联想、突破常规、创新方案',
    prerequisites: [],
    relatedSkills: [],
    nextSkills: [],
    complementary: [],
    demandLevel: 'high',
    learningCurve: 2,
    timeToLearn: '持续练习',
    relevantCareers: ['cco_ai_engineer', 'cco_ai_product_manager', 'cco_content_editor'],
    evidence: [{ type: 'expert', source: '人工维护', date: '2024-01-01', confidence: 0.8 }],
    source: '人工维护',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: SKILL_IDS.execution,
    version: '1.0.0',
    name: '执行力',
    aliases: ['执行', 'Execution', '交付能力', '执行力'],
    category: '软技能',
    subcategory: '通用',
    description: '高效执行：目标拆解、时间管理、结果导向、持续跟进',
    prerequisites: [],
    relatedSkills: [],
    nextSkills: [],
    complementary: [],
    demandLevel: 'high',
    learningCurve: 2,
    timeToLearn: '持续练习',
    relevantCareers: [],
    evidence: [{ type: 'expert', source: '人工维护', date: '2024-01-01', confidence: 0.8 }],
    source: '人工维护',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: SKILL_IDS.leadership,
    version: '1.0.0',
    name: '领导力',
    aliases: ['领导', 'Leadership', '管理能力', 'Team Leadership'],
    category: '软技能',
    subcategory: '通用',
    description: '团队领导：愿景塑造、激励赋能、决策担当、培养他人',
    prerequisites: [
      { skillId: SKILL_IDS.communication, weight: 0.8, type: 'prerequisite' },
    ],
    relatedSkills: [
      { skillId: SKILL_IDS.communication, weight: 0.8, type: 'related' },
    ],
    nextSkills: [],
    complementary: [],
    demandLevel: 'high',
    learningCurve: 3,
    timeToLearn: '持续练习',
    relevantCareers: [],
    evidence: [{ type: 'expert', source: '人工维护', date: '2024-01-01', confidence: 0.8 }],
    source: '人工维护',
    updatedAt: '2024-01-01T00:00:00Z',
  },
]

// ─── 技能图统计 ───

export const SKILL_GRAPH_STATS = {
  totalSkills: CORE_SKILLS.length,
  categories: {
    'AI/LLM': CORE_SKILLS.filter(s => s.subcategory === 'AI核心' || s.subcategory === 'AI应用' || s.subcategory === 'AI运维' || s.subcategory === 'AI治理' || s.subcategory === 'AI协议' || s.subcategory === 'LLM框架').length,
    '编程语言': CORE_SKILLS.filter(s => s.category === '语言').length,
    '前端': CORE_SKILLS.filter(s => s.subcategory === '前端框架' || s.subcategory === '全栈框架' || s.subcategory === 'CSS框架' || s.subcategory === '标记语言').length,
    '后端': CORE_SKILLS.filter(s => s.subcategory === '后端运行时' || s.subcategory === '后端框架' || s.subcategory === 'ORM').length,
    '数据库': CORE_SKILLS.filter(s => s.subcategory === '关系型数据库' || s.subcategory === '缓存数据库' || s.subcategory === '数据库').length,
    'DevOps': CORE_SKILLS.filter(s => s.subcategory === '容器化' || s.subcategory === '容器编排' || s.subcategory === 'DevOps' || s.subcategory === '操作系统' || s.subcategory === 'Web服务器' || s.subcategory === '云平台').length,
    '数据分析': CORE_SKILLS.filter(s => s.subcategory === '数据科学' || s.subcategory === '数据处理' || s.subcategory === '数值计算' || s.subcategory === '可视化' || s.subcategory === '数学').length,
    '产品': CORE_SKILLS.filter(s => s.subcategory === '产品' || s.subcategory === '研发管理').length,
    '软技能': CORE_SKILLS.filter(s => s.category === '软技能').length,
  },
  totalEdges: CORE_SKILLS.reduce((sum, s) => sum + s.prerequisites.length + s.relatedSkills.length + s.nextSkills.length + s.complementary.length, 0),
  avgConnectionsPerSkill: Math.round(CORE_SKILLS.reduce((sum, s) => sum + s.prerequisites.length + s.relatedSkills.length + s.nextSkills.length + s.complementary.length, 0) / CORE_SKILLS.length * 10) / 10,
}
