// 初始化全量模型供应商配置 — 图片/视频/语音/文字
import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

const providers = [
  // ────────── 图片模型 ──────────
  {
    provider: 'aliyun_image',
    label: '阿里百炼·文生图',
    modelType: 'image',
    modelName: 'wanx2.1-t2i-turbo',
    apiKeyEnv: 'ALIYUN_API_KEY',
    endpoint: 'https://dashscope.aliyuncs.com/api/v1/services/aigc/text2image/image-synthesis',
    aspectRatioMap: { '16:9': '1280x720', '9:16': '720x1280', '1:1': '1024x1024' },
    defaultParams: { n: 1, steps: 20, negativePrompt: '模糊, 变形, 多余肢体, 文字, 水印' },
    sortOrder: 1,
  },
  {
    provider: 'aliyun_image_plus',
    label: '阿里百炼·图生图',
    modelType: 'image',
    modelName: 'wanx2.1-t2i-turbo',
    apiKeyEnv: 'ALIYUN_API_KEY',
    endpoint: 'https://dashscope.aliyuncs.com/api/v1/services/aigc/text2image/image-synthesis',
    aspectRatioMap: { '16:9': '1280x720', '9:16': '720x1280', '1:1': '1024x1024' },
    defaultParams: { n: 1, steps: 20, mode: 'img2img', negativePrompt: '模糊, 变形' },
    sortOrder: 2,
  },
  {
    provider: 'volcengine_image',
    label: '火山引擎·文生图',
    modelType: 'image',
    modelName: 'doubao-image-pro',
    apiKeyEnv: 'VOLCENGINE_API_KEY',
    endpoint: '',
    aspectRatioMap: { '16:9': '1920x1080', '9:16': '1080x1920', '1:1': '1024x1024' },
    defaultParams: { n: 1 },
    sortOrder: 3,
  },
  {
    provider: 'replicate_flux',
    label: 'Replicate·Flux',
    modelType: 'image',
    modelName: 'black-forest-labs/flux-schnell',
    apiKeyEnv: 'REPLICATE_API_KEY',
    endpoint: 'https://api.replicate.com/v1/predictions',
    aspectRatioMap: { '16:9': '1024x576', '9:16': '576x1024', '1:1': '1024x1024' },
    defaultParams: { n: 1, steps: 4 },
    sortOrder: 4,
  },
  {
    provider: 'replicate_flux_pro',
    label: 'Replicate·Flux Pro',
    modelType: 'image',
    modelName: 'black-forest-labs/flux-1.1-pro',
    apiKeyEnv: 'REPLICATE_API_KEY',
    endpoint: 'https://api.replicate.com/v1/predictions',
    aspectRatioMap: { '16:9': '1024x576', '9:16': '576x1024' },
    defaultParams: { n: 1, steps: 25 },
    sortOrder: 5,
  },
  {
    provider: 'openai_dalle',
    label: 'OpenAI·DALL-E 3',
    modelType: 'image',
    modelName: 'dall-e-3',
    apiKeyEnv: 'OPENAI_API_KEY',
    endpoint: 'https://api.openai.com/v1/images/generations',
    aspectRatioMap: { '16:9': '1792x1024', '9:16': '1024x1792', '1:1': '1024x1024' },
    defaultParams: { n: 1, quality: 'hd', style: 'vivid' },
    sortOrder: 6,
  },
  {
    provider: 'siliconflow_image',
    label: 'SiliconFlow·文生图',
    modelType: 'image',
    modelName: 'stabilityai/stable-diffusion-3-5-large',
    apiKeyEnv: 'SILICONFLOW_API_KEY',
    endpoint: '',
    aspectRatioMap: { '16:9': '1024x576', '9:16': '576x1024' },
    defaultParams: { n: 1, steps: 20 },
    sortOrder: 7,
  },

  // ────────── 视频模型 ──────────
  {
    provider: 'volcengine_video',
    label: '火山引擎·视频生成',
    modelType: 'video',
    modelName: 'doubao-video-pro',
    apiKeyEnv: 'VOLCENGINE_API_KEY',
    endpoint: '',
    aspectRatioMap: { '16:9': '1920x1080', '9:16': '1080x1920' },
    defaultParams: { n: 1, duration: 5, fps: 24 },
    sortOrder: 10,
  },
  {
    provider: 'aliyun_video',
    label: '阿里百炼·视频生成',
    modelType: 'video',
    modelName: 'wan2.1-video-pro',
    apiKeyEnv: 'ALIYUN_API_KEY',
    endpoint: 'https://dashscope.aliyuncs.com/api/v1/services/aigc/video-generation/video-synthesis',
    aspectRatioMap: { '16:9': '1280x720', '9:16': '720x1280' },
    defaultParams: { n: 1, duration: 5 },
    sortOrder: 11,
  },
  {
    provider: 'replicate_video',
    label: 'Replicate·视频生成',
    modelType: 'video',
    modelName: 'minimax/video-01',
    apiKeyEnv: 'REPLICATE_API_KEY',
    endpoint: '',
    aspectRatioMap: { '16:9': '1920x1080', '9:16': '1080x1920' },
    defaultParams: { n: 1, duration: 5 },
    sortOrder: 12,
  },
  {
    provider: 'kling_video',
    label: '可灵·视频生成',
    modelType: 'video',
    modelName: 'kling-video-1.6',
    apiKeyEnv: 'KLING_API_KEY',
    endpoint: '',
    aspectRatioMap: { '16:9': '1920x1080', '9:16': '1080x1920' },
    defaultParams: { n: 1, duration: 5 },
    sortOrder: 13,
  },

  // ────────── 语音/TTS 模型 ──────────
  {
    provider: 'aliyun_tts',
    label: '阿里百炼·语音合成',
    modelType: 'tts',
    modelName: 'cosyvoice-v1',
    apiKeyEnv: 'ALIYUN_API_KEY',
    endpoint: 'https://dashscope.aliyuncs.com/api/v1/services/tts/text-to-speech',
    defaultParams: { speed: 1.0, pitch: 0, format: 'mp3', sampleRate: 24000 },
    sortOrder: 20,
  },
  {
    provider: 'volcengine_tts',
    label: '火山引擎·语音合成',
    modelType: 'tts',
    modelName: 'doubao-tts-pro',
    apiKeyEnv: 'VOLCENGINE_API_KEY',
    endpoint: '',
    defaultParams: { speed: 1.0, pitch: 0, format: 'mp3' },
    sortOrder: 21,
  },
  {
    provider: 'openai_tts',
    label: 'OpenAI·语音合成',
    modelType: 'tts',
    modelName: 'tts-1',
    apiKeyEnv: 'OPENAI_API_KEY',
    endpoint: 'https://api.openai.com/v1/audio/speech',
    defaultParams: { voice: 'alloy', speed: 1.0, format: 'mp3' },
    sortOrder: 22,
  },
  {
    provider: 'siliconflow_tts',
    label: 'SiliconFlow·语音合成',
    modelType: 'tts',
    modelName: 'FunAudioLLM/CosyVoice2-0.5B',
    apiKeyEnv: 'SILICONFLOW_API_KEY',
    endpoint: '',
    defaultParams: { speed: 1.0, format: 'wav' },
    sortOrder: 23,
  },

  // ────────── 语音识别/ASR ──────────
  {
    provider: 'aliyun_asr',
    label: '阿里百炼·语音识别',
    modelType: 'asr',
    modelName: 'paraformer-realtime-v2',
    apiKeyEnv: 'ALIYUN_API_KEY',
    endpoint: 'https://dashscope.aliyuncs.com/api/v1/services/asr/transcription',
    defaultParams: { format: 'pcm', sampleRate: 16000 },
    sortOrder: 30,
  },
  {
    provider: 'volcengine_asr',
    label: '火山引擎·语音识别',
    modelType: 'asr',
    modelName: 'doubao-asr-pro',
    apiKeyEnv: 'VOLCENGINE_API_KEY',
    endpoint: '',
    defaultParams: { format: 'pcm', sampleRate: 16000 },
    sortOrder: 31,
  },

  // ────────── 文字/LLM 大模型 ──────────
  {
    provider: 'aliyun_llm',
    label: '阿里百炼·通义千问',
    modelType: 'llm',
    modelName: 'qwen-max-2025-01-25',
    apiKeyEnv: 'ALIYUN_API_KEY',
    endpoint: 'https://dashscope.aliyuncs.com/compatible-mode/v1',
    defaultParams: { temperature: 0.7, maxTokens: 4096, topP: 0.9 },
    sortOrder: 40,
  },
  {
    provider: 'aliyun_qwen_turbo',
    label: '阿里百炼·Qwen-Turbo',
    modelType: 'llm',
    modelName: 'qwen-turbo-latest',
    apiKeyEnv: 'ALIYUN_API_KEY',
    endpoint: 'https://dashscope.aliyuncs.com/compatible-mode/v1',
    defaultParams: { temperature: 0.7, maxTokens: 8192, topP: 0.9 },
    sortOrder: 41,
  },
  {
    provider: 'volcengine_llm',
    label: '火山引擎·豆包',
    modelType: 'llm',
    modelName: 'doubao-pro-32k',
    apiKeyEnv: 'VOLCENGINE_API_KEY',
    endpoint: '',
    defaultParams: { temperature: 0.7, maxTokens: 4096, topP: 0.9 },
    sortOrder: 42,
  },
  {
    provider: 'deepseek',
    label: 'DeepSeek·V3',
    modelType: 'llm',
    modelName: 'deepseek-chat',
    apiKeyEnv: 'DEEPSEEK_API_KEY',
    endpoint: 'https://api.deepseek.com/v1',
    defaultParams: { temperature: 0.7, maxTokens: 8192, topP: 0.9 },
    sortOrder: 43,
  },
  {
    provider: 'deepseek_r1',
    label: 'DeepSeek·R1',
    modelType: 'llm',
    modelName: 'deepseek-reasoner',
    apiKeyEnv: 'DEEPSEEK_API_KEY',
    endpoint: 'https://api.deepseek.com/v1',
    defaultParams: { temperature: 0.6, maxTokens: 8192, topP: 0.95 },
    sortOrder: 44,
  },
  {
    provider: 'openai_llm',
    label: 'OpenAI·GPT-4o',
    modelType: 'llm',
    modelName: 'gpt-4o',
    apiKeyEnv: 'OPENAI_API_KEY',
    endpoint: 'https://api.openai.com/v1',
    defaultParams: { temperature: 0.7, maxTokens: 4096, topP: 0.9 },
    sortOrder: 45,
  },
  {
    provider: 'openai_o3',
    label: 'OpenAI·o3-mini',
    modelType: 'llm',
    modelName: 'o3-mini',
    apiKeyEnv: 'OPENAI_API_KEY',
    endpoint: 'https://api.openai.com/v1',
    defaultParams: { temperature: 1.0, maxTokens: 16384 },
    sortOrder: 46,
  },
  {
    provider: 'siliconflow_llm',
    label: 'SiliconFlow·通用',
    modelType: 'llm',
    modelName: 'deepseek-ai/DeepSeek-V2.5',
    apiKeyEnv: 'SILICONFLOW_API_KEY',
    endpoint: '',
    defaultParams: { temperature: 0.7, maxTokens: 4096, topP: 0.9 },
    sortOrder: 47,
  },
  {
    provider: 'kimi_llm',
    label: '月之暗面·Kimi',
    modelType: 'llm',
    modelName: 'moonshot-v1-128k',
    apiKeyEnv: 'KIMI_API_KEY',
    endpoint: '',
    defaultParams: { temperature: 0.3, maxTokens: 4096 },
    sortOrder: 48,
  },
  {
    provider: 'claude_llm',
    label: 'Anthropic·Claude',
    modelType: 'llm',
    modelName: 'claude-sonnet-4-20250514',
    apiKeyEnv: 'CLAUDE_API_KEY',
    endpoint: '',
    defaultParams: { temperature: 0.7, maxTokens: 8192 },
    sortOrder: 49,
  },
]

async function main() {
  let count = 0
  for (const p of providers) {
    await prisma.modelProvider.upsert({
      where: { provider: p.provider },
      update: { ...p },
      create: { ...p },
    })
    count++
  }
  console.log(`✓ 已初始化 ${count} 个模型配置`)
  // 展示分类统计
  const groups = await prisma.modelProvider.groupBy({
    by: ['modelType'],
    _count: true,
  })
  for (const g of groups) {
    console.log(`  ${g.modelType.padEnd(6)}: ${g._count} 个`)
  }
}

main().catch(console.error).finally(() => prisma.$disconnect())
